/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import DTO.PesquisarFuncionarioDTO;
import Modelo.CadastrarFuncionarioControle;
import com.sun.org.apache.xml.internal.utils.ObjectStack;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class frmCadastrarFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form frmManutencaoo
     */
    public frmCadastrarFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtExpedicao.setText("SSP/SP");
        txtCidade.setText("QUADRA/SP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        lblExpedicao = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblDataAdmissao = new javax.swing.JLabel();
        lblReferencia = new javax.swing.JLabel();
        lblFuncaoGratificada = new javax.swing.JLabel();
        txtFuncaoGratificada = new javax.swing.JTextField();
        lblSr = new javax.swing.JLabel();
        cmbSr = new javax.swing.JComboBox<>();
        txtExpedicao = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        lblInstrucao = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        lblNaturalidade = new javax.swing.JLabel();
        txtCNH = new javax.swing.JTextField();
        lblCNH = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblCelUm = new javax.swing.JLabel();
        lblCelDois = new javax.swing.JLabel();
        lblCelTres = new javax.swing.JLabel();
        txtTituloEleitor = new javax.swing.JTextField();
        lblTituloEleitor = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtDataAdmissao = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        txtCelUm = new javax.swing.JFormattedTextField();
        txtCelDois = new javax.swing.JFormattedTextField();
        txtCelTres = new javax.swing.JFormattedTextField();
        cmbInstrucao = new javax.swing.JComboBox<>();
        cmbEstadoCivil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);

        lblMatricula.setText("Matrícula: ");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");

        lblNome.setText("Nome:");

        lblEndereco.setText("Endereço:");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        lblNumero.setText("Número:");

        lblCargo.setText("Cargo/Emprego");

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBairroFocusLost(evt);
            }
        });
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        lblBairro.setText("Bairro:");

        txtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCargoFocusLost(evt);
            }
        });
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRGFocusLost(evt);
            }
        });
        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });

        lblRG.setText("RG:");

        txtReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReferenciaFocusLost(evt);
            }
        });
        txtReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaActionPerformed(evt);
            }
        });

        lblExpedicao.setText("Exp.:");

        lblDataNascimento.setText("Dt Nascimento");

        lblDataAdmissao.setText("Dt Admissão:");

        lblReferencia.setText("Referência");

        lblFuncaoGratificada.setText("Função Gratificada");

        txtFuncaoGratificada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFuncaoGratificadaFocusLost(evt);
            }
        });
        txtFuncaoGratificada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncaoGratificadaActionPerformed(evt);
            }
        });

        lblSr.setText("Sr.:");

        cmbSr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SR.", "SRA." }));
        cmbSr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSrActionPerformed(evt);
            }
        });

        txtExpedicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpedicaoFocusLost(evt);
            }
        });
        txtExpedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpedicaoActionPerformed(evt);
            }
        });

        lblEstadoCivil.setText("Estado Civil");

        lblInstrucao.setText("Instrução");

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        txtNaturalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNaturalidadeFocusLost(evt);
            }
        });
        txtNaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaturalidadeActionPerformed(evt);
            }
        });

        lblNaturalidade.setText("Naturalidade:");

        txtCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNHActionPerformed(evt);
            }
        });

        lblCNH.setText("CNH:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setText("E-mail:");

        lblCelUm.setText("Cel 1");

        lblCelDois.setText("Cel 2");

        lblCelTres.setText("Cel 3");

        txtTituloEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloEleitorActionPerformed(evt);
            }
        });

        lblTituloEleitor.setText("Título de Eleitor");

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        try {
            txtDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataAdmissaoFocusLost(evt);
            }
        });
        txtDataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAdmissaoActionPerformed(evt);
            }
        });
        txtDataAdmissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataAdmissaoKeyPressed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setToolTipText("");
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        txtDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataNascimentoKeyPressed(evt);
            }
        });

        try {
            txtCelUm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelUm.setText("   ");
        txtCelUm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelUmFocusLost(evt);
            }
        });
        txtCelUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelUmActionPerformed(evt);
            }
        });
        txtCelUm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelUmKeyPressed(evt);
            }
        });

        try {
            txtCelDois.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelDois.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelDoisFocusLost(evt);
            }
        });
        txtCelDois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelDoisKeyPressed(evt);
            }
        });

        try {
            txtCelTres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelTres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelTresFocusLost(evt);
            }
        });
        txtCelTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelTresActionPerformed(evt);
            }
        });
        txtCelTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelTresKeyPressed(evt);
            }
        });

        cmbInstrucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNDAMENTAL I - 1º AO 5º ANO - INCOMPLETO", "FUNDAMENTAL I - 1º AO 5º ANO - COMPLETO", "FUNDAMENTAL II -  6º AO 9º ANO - INCOMPLETO", "FUNDAMENTAL II -  6º AO 9º ANO - COMPLETO", "ENSINO MÉDIO - INCOMPLETO", "ENSINO MÉDIO - COMPLETO", "ENSINO TÉCNICO - INCOMPLETO", "ENSINO TÉCNICO - COMPLETO", "ENSINO SUPERIOR - INCOMPLETO", "ENSINO SUPERIOR - COMPLETO" }));
        cmbInstrucao.setSelectedIndex(5);
        cmbInstrucao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbInstrucaoKeyPressed(evt);
            }
        });

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO", "CASADO", "SEPARADO", "DIRVOCIADO", "VIÚVO" }));
        cmbEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbEstadoCivilKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataAdmissao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE))
                            .addComponent(txtDataAdmissao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataNascimento)
                                    .addComponent(txtDataNascimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCargo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReferencia)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRG)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblExpedicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNaturalidade)
                                    .addComponent(txtNaturalidade))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFuncaoGratificada)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFuncaoGratificada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEstadoCivil)
                                    .addComponent(cmbEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInstrucao)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cmbInstrucao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEndereco)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(lblCPF)
                            .addComponent(txtCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBairro)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCidade)
                                    .addComponent(txtCidade)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCNH)
                                    .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloEleitor)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtTituloEleitor)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelUm, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelUm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelDois, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCelDois))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelTres)
                            .addComponent(txtCelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblSr)
                            .addComponent(lblMatricula))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDataAdmissao)
                        .addGap(1, 1, 1)
                        .addComponent(txtDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExpedicao)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDataNascimento)
                                        .addComponent(lblCargo, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblFuncaoGratificada))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblReferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuncaoGratificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRG)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEstadoCivil)
                                        .addComponent(lblInstrucao)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNaturalidade)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCPF)
                            .addComponent(lblCNH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloEleitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEndereco)
                                .addComponent(lblBairro, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCelUm)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCelUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCelDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblCelDois))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(lblCelTres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        txtExpedicao.requestFocus();
    }//GEN-LAST:event_txtRGActionPerformed

    private void cmbSrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSrActionPerformed
        // TODO add your handling code here:
        if(cmbSr.getSelectedItem().equals("SR."))
        {
            String estadoCivil[] = {"SOLTEIRO", "CASADO", "SEPARADO", "DIVORCIADO", "VIÚVO"};
            final DefaultComboBoxModel model = new DefaultComboBoxModel(estadoCivil);
            
            cmbEstadoCivil.setModel(model);
        }
        else if(cmbSr.getSelectedItem().equals("SRA."))
        {
            String estadoCivil[] = {"SOLTEIRA", "CASADA", "SEPARADA", "DIVORCIADA", "VIÚVA"};
            final DefaultComboBoxModel model = new DefaultComboBoxModel(estadoCivil);
            
            cmbEstadoCivil.setModel(model);
        }      
        
        txtNome.requestFocus();
    }//GEN-LAST:event_cmbSrActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        botaoCadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void botaoCadastrar()
    {
        //CÓDIGO BOTÃO CADASTRAR
        //pegar item de combobox
        String cmbPronomeDeTratamentoConvertidoParaString = (String) this.cmbSr.getSelectedItem();
        String cmbInstrucao = (String) this.cmbInstrucao.getSelectedItem();
        String cmbEstadoCivil = (String) this.cmbEstadoCivil.getSelectedItem();       

        //verificar se tem algum valor digitado no txtbox
        validarSeCamposEstaoComValores();
                
       if(!txtMatricula.getText().isEmpty() && !txtNome.getText().isEmpty() && !txtDataAdmissao.getText().equals("  /  /    ") && !txtDataNascimento.getText().equals("  /  /    ") && !txtCargo.getText().isEmpty() && !txtReferencia.getText().isEmpty() && !txtRG.getText().isEmpty() && !txtExpedicao.getText().isEmpty() && !txtNaturalidade.getText().isEmpty() && !cmbEstadoCivil.isEmpty() && !cmbInstrucao.isEmpty() && !txtCPF.getText().equals("   .   .   -  ") && !txtEndereco.getText().isEmpty() && !txtNumero.getText().isEmpty() && !txtBairro.getText().isEmpty() && !txtCidade.getText().isEmpty() && !txtCelUm.getText().equals("(  )       -    "))
       {
         //txtCelDois.getText().equals("(  )       -    ")) ? "" : txtCelDois.getText() operador ternario se txtcel dois tiver numero cadastrado pegue, senão deixe em branco
         CadastrarFuncionarioControle controle = new CadastrarFuncionarioControle(txtMatricula.getText(), cmbPronomeDeTratamentoConvertidoParaString, txtNome.getText(), txtDataAdmissao.getText(), txtDataNascimento.getText(), txtCargo.getText(), txtReferencia.getText(), txtFuncaoGratificada.getText(), txtRG.getText(), txtExpedicao.getText(), txtNaturalidade.getText(), cmbEstadoCivil, cmbInstrucao, txtCPF.getText(), txtCNH.getText(), (txtTituloEleitor.getText().isEmpty()) ? "" : txtTituloEleitor.getText(), txtEndereco.getText(), txtNumero.getText(), txtBairro.getText(), txtCidade.getText(), txtCelUm.getText(), (txtCelDois.getText().equals("(  )       -    ")) ? "" : txtCelDois.getText(), (txtCelTres.getText().equals("(  )       -    ")) ? "" : txtCelTres.getText(), (txtEmail.getText().isEmpty()) ? "" : txtEmail.getText());  
         if(controle.getMensagem().equals("ok"))
         {
             JOptionPane.showMessageDialog(null, "CADASTRO REALIZADO COM SUCESSO!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
             reiniciarCampos(); 
         }
         else if(controle.getMensagem().equals("erro 1"))
         {
             JOptionPane.showMessageDialog(null, "FUNCIONÁRIO JÁ CADASTRADO NO BANCO DE DADOS.","ERRO",JOptionPane.ERROR_MESSAGE);
         }
       }
    }
    
    private void validarSeCamposEstaoComValores()
    {
       if(txtMatricula.getText().isEmpty())
       {
           lblMatricula.setForeground(Color.red);
       }
       else
       {
           lblMatricula.setForeground(Color.black);
       }

       if(txtNome.getText().isEmpty())
       {
           lblNome.setForeground(Color.red);
       }
       else
       {
           lblNome.setForeground(Color.black);
       }

       if(txtDataAdmissao.getText().equals("  /  /    "))
       {
           lblDataAdmissao.setForeground(Color.red);
       }
       else
       {
           lblDataAdmissao.setForeground(Color.black);
       }

       if(txtDataNascimento.getText().equals("  /  /    "))
       {
           lblDataNascimento.setForeground(Color.red);
       }
       else
       {
           lblDataNascimento.setForeground(Color.black);
       }

       if(txtCargo.getText().isEmpty())
       {
           lblCargo.setForeground(Color.red);
       }
       else
       {
           lblCargo.setForeground(Color.black);
       }

       if(txtReferencia.getText().isEmpty())
       {
           lblReferencia.setForeground(Color.red);
       }
       else
       {
           lblReferencia.setForeground(Color.black);
       }

       if(txtRG.getText().isEmpty())
       {
           lblRG.setForeground(Color.red);
       }
       else
       {
           lblRG.setForeground(Color.black);
       }

       if(txtExpedicao.getText().isEmpty())
       {
           lblExpedicao.setForeground(Color.red);
       }
       else
       {
           lblExpedicao.setForeground(Color.black);
       }

       if(txtNaturalidade.getText().isEmpty())
       {
           lblNaturalidade.setForeground(Color.red);
       }
       else
       {
           lblNaturalidade.setForeground(Color.black);
       }

       if(txtCPF.getText().equals("   .   .   -  "))
       {
           lblCPF.setForeground(Color.red);
       }
       else
       {
           lblCPF.setForeground(Color.black);
       }

       if(txtEndereco.getText().isEmpty())
       {
           lblEndereco.setForeground(Color.red);
       }
       else
       {
           lblEndereco.setForeground(Color.black);
       }

       if(txtNumero.getText().isEmpty())
       {
           lblNumero.setForeground(Color.red);
       }
       else
       {
           lblNumero.setForeground(Color.black);
       }

       if(txtBairro.getText().isEmpty())
       {
           lblBairro.setForeground(Color.red);
       }
       else
       {
           lblBairro.setForeground(Color.black);
       }

       if(txtCidade.getText().isEmpty())
       {
           lblCidade.setForeground(Color.red);
       }
       else
       {
           lblCidade.setForeground(Color.black);
       }

       if(txtCelUm.getText().equals("(  )       -    "))
       {
           lblCelUm.setForeground(Color.red);
       }
       else
       {
           lblCelUm.setForeground(Color.black);
       }
    }
    
    public void reiniciarCampos()
    {
        txtMatricula.setText("");
        cmbSr.setSelectedIndex(0);
        txtNome.setText("");
        txtDataAdmissao.setValue("");
        txtDataNascimento.setValue("");
        txtCargo.setText("");
        txtReferencia.setText("");
        txtFuncaoGratificada.setText("");
        txtRG.setText("");
        txtExpedicao.setText("");
        txtNaturalidade.setText("");
        cmbEstadoCivil.setSelectedIndex(0);
        cmbInstrucao.setSelectedIndex(5);
        txtCPF.setValue("");
        txtCNH.setText("");
        txtTituloEleitor.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCelUm.setValue("");
        txtCelDois.setValue("");
        txtCelTres.setValue("");
        txtEmail.setText("");  
    }    
   
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        frmPesquisarFuncionario frmPF = new frmPesquisarFuncionario(null, true);
        frmPF.setVisible(true);
        
        if(frmPF.getMensagem().equals("pode passar"))
        {        
            txtMatricula.setText(frmPF.getLista().get(frmPF.getIndex()).getMatricula());
            cmbSr.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getPronomeTratamento());
            txtNome.setText(frmPF.getLista().get(frmPF.getIndex()).getNome());
            txtDataAdmissao.setText(frmPF.getLista().get(frmPF.getIndex()).getDataAdmissao());
            txtDataNascimento.setText(frmPF.getLista().get(frmPF.getIndex()).getDataNascimento());
            txtCargo.setText(frmPF.getLista().get(frmPF.getIndex()).getCargo());
            txtReferencia.setText(frmPF.getLista().get(frmPF.getIndex()).getReferencia());
            txtRG.setText(frmPF.getLista().get(frmPF.getIndex()).getRg());
            txtNaturalidade.setText(frmPF.getLista().get(frmPF.getIndex()).getNaturalidade());
            cmbEstadoCivil.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getEstadoCivil());
            cmbInstrucao.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getInstrucao());
            txtCPF.setText(frmPF.getLista().get(frmPF.getIndex()).getCpf());
            txtCNH.setText(frmPF.getLista().get(frmPF.getIndex()).getCnh());
            txtTituloEleitor.setText(frmPF.getLista().get(frmPF.getIndex()).getTituloEleitor());
            txtEndereco.setText(frmPF.getLista().get(frmPF.getIndex()).getEndereco());
            txtNumero.setText(frmPF.getLista().get(frmPF.getIndex()).getNumero());
            txtBairro.setText(frmPF.getLista().get(frmPF.getIndex()).getBairro());
            txtCidade.setText(frmPF.getLista().get(frmPF.getIndex()).getCidade());
            txtCelUm.setText(frmPF.getLista().get(frmPF.getIndex()).getCelUm());
            txtCelDois.setText(frmPF.getLista().get(frmPF.getIndex()).getCelDois());
            txtCelTres.setText(frmPF.getLista().get(frmPF.getIndex()).getCelTres()); 
            txtEmail.setText(frmPF.getLista().get(frmPF.getIndex()).getEmail()); 
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
        txtNome.requestFocus();
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        txtDataAdmissao.requestFocus();
        String mudarParaCaixaAlta = txtNome.getText().toUpperCase();
        txtNome.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        txtReferencia.requestFocus();
        String mudarParaCaixaAlta = txtCargo.getText().toUpperCase();
        txtCargo.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtFuncaoGratificadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncaoGratificadaActionPerformed
        txtRG.requestFocus();
        String mudarParaCaixaAlta = txtFuncaoGratificada.getText().toUpperCase();
        txtFuncaoGratificada.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtFuncaoGratificadaActionPerformed

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
        txtFuncaoGratificada.requestFocus();
        String mudarParaCaixaAlta = txtReferencia.getText().toUpperCase();
        txtReferencia.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void txtExpedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpedicaoActionPerformed
        txtNaturalidade.requestFocus();
        String mudarParaCaixaAlta = txtExpedicao.getText().toUpperCase();
        txtExpedicao.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtExpedicaoActionPerformed

    private void txtNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeActionPerformed
        cmbEstadoCivil.requestFocus();
        String mudarParaCaixaAlta = txtNaturalidade.getText().toUpperCase();
        txtNaturalidade.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNaturalidadeActionPerformed

    private void txtCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNHActionPerformed
        txtTituloEleitor.requestFocus();
        String mudarParaCaixaAlta = txtTituloEleitor.getText().toUpperCase();
        txtTituloEleitor.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCNHActionPerformed

    private void txtTituloEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloEleitorActionPerformed
        txtEndereco.requestFocus();
        String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
        txtEndereco.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtTituloEleitorActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        txtBairro.requestFocus();
        String mudarParaCaixaAlta = txtNumero.getText().toUpperCase();
        txtNumero.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        txtNumero.requestFocus();
        String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
        txtEndereco.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        txtCidade.requestFocus();
        String mudarParaCaixaAlta = txtBairro.getText().toUpperCase();
        txtBairro.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        txtCelUm.requestFocus();
        String mudarParaCaixaAlta = txtCidade.getText().toUpperCase();
        txtCidade.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        btnCadastrar.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
       if(txtNome.getText().isEmpty())
       {
           lblNome.setForeground(Color.red);           
       }
       else
       {
           lblNome.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNome.getText().toUpperCase();
           txtNome.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusLost
     if(txtCargo.getText().isEmpty())
       {
           lblCargo.setForeground(Color.red);
       }
       else
       {
           lblCargo.setForeground(Color.black);
           String mudarParaCaixaAlta = txtCargo.getText().toUpperCase();
           txtCargo.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtCargoFocusLost

    private void txtReferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReferenciaFocusLost
       if(txtReferencia.getText().isEmpty())
       {
           lblReferencia.setForeground(Color.red);
       }
       else
       {
           lblReferencia.setForeground(Color.black);
           String mudarParaCaixaAlta = txtReferencia.getText().toUpperCase();
           txtReferencia.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtReferenciaFocusLost

    private void txtFuncaoGratificadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFuncaoGratificadaFocusLost
           lblFuncaoGratificada.setForeground(Color.black);
           String mudarParaCaixaAlta = txtFuncaoGratificada.getText().toUpperCase();
           txtFuncaoGratificada.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtFuncaoGratificadaFocusLost

    private void txtRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusLost
         if(txtRG.getText().isEmpty())
       {
           lblRG.setForeground(Color.red);
       }
       else
       {
           lblRG.setForeground(Color.black);
           String mudarParaCaixaAlta = txtRG.getText().toUpperCase();
           txtRG.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtRGFocusLost

    private void txtExpedicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpedicaoFocusLost
       if(txtExpedicao.getText().isEmpty())
       {
           lblExpedicao.setForeground(Color.red);
       }
       else
       {
           lblExpedicao.setForeground(Color.black);
           String mudarParaCaixaAlta = txtExpedicao.getText().toUpperCase();
           txtExpedicao.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtExpedicaoFocusLost

    private void txtNaturalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNaturalidadeFocusLost
        if(txtNaturalidade.getText().isEmpty())
       {
           lblNaturalidade.setForeground(Color.red);
       }
       else
       {
           lblNaturalidade.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNaturalidade.getText().toUpperCase();
           txtNaturalidade.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNaturalidadeFocusLost

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        if(txtEndereco.getText().isEmpty())
       {
           lblEndereco.setForeground(Color.red);
       }
       else
       {
           lblEndereco.setForeground(Color.black);
           String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
           txtEndereco.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
      if(txtNumero.getText().isEmpty())
       {
           lblNumero.setForeground(Color.red);
       }
       else
       {
           lblNumero.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNumero.getText().toUpperCase();
           txtNumero.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusLost
        if(txtBairro.getText().isEmpty())
       {
           lblBairro.setForeground(Color.red);
       }
       else
       {
           lblBairro.setForeground(Color.black);
           String mudarParaCaixaAlta = txtBairro.getText().toUpperCase();
           txtBairro.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtBairroFocusLost

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        if(txtCidade.getText().isEmpty())
       {
           lblCidade.setForeground(Color.red);
       }
       else
       {
           lblCidade.setForeground(Color.black);
           String mudarParaCaixaAlta = txtCidade.getText().toUpperCase();
           txtCidade.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
           botaoCadastrar();
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    private void txtDataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAdmissaoActionPerformed
        txtDataNascimento.requestFocus();
      
    }//GEN-LAST:event_txtDataAdmissaoActionPerformed
    private void txtDataAdmissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataAdmissaoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtDataNascimento.requestFocus();
    }   
    }//GEN-LAST:event_txtDataAdmissaoKeyPressed

    private void txtDataAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataAdmissaoFocusLost
    if(txtDataAdmissao.getText().equals("  /  /    "))
    {
        lblDataAdmissao.setForeground(Color.red);
        txtDataAdmissao.setValue("");
    }
    else
    {
        lblDataAdmissao.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtDataAdmissaoFocusLost

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
    if(txtCPF.getText().equals("   .   .   -  "))
    {
        lblCPF.setForeground(Color.red);
        txtCPF.setValue("");
    }  
    else
    {
        lblCPF.setForeground(Color.black);
    }
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
       txtCNH.requestFocus();
    }
    }//GEN-LAST:event_txtCPFKeyPressed

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
    if(txtDataNascimento.getText().equals("  /  /    "))
    {
       lblDataNascimento.setForeground(Color.red);
       txtDataNascimento.setValue("");
    }
    else
    {
        lblDataNascimento.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        txtCargo.requestFocus();
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void txtDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataNascimentoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCargo.requestFocus();
    }
    }//GEN-LAST:event_txtDataNascimentoKeyPressed

    private void txtCelUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelUmActionPerformed
        txtCelDois.requestFocus();
    }//GEN-LAST:event_txtCelUmActionPerformed

    private void txtCelUmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelUmFocusLost
    if(txtCelUm.getText().equals("(  )       -    "))
    {
        lblCelUm.setForeground(Color.red);
        txtCelUm.setValue("");
    }
    else
    {
        lblCelUm.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtCelUmFocusLost

    private void txtCelUmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelUmKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCelDois.requestFocus();
    }
    }//GEN-LAST:event_txtCelUmKeyPressed

    private void txtCelDoisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelDoisKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCelTres.requestFocus();
    }
    }//GEN-LAST:event_txtCelDoisKeyPressed

    private void txtCelTresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelTresKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtEmail.requestFocus();
    }        
    }//GEN-LAST:event_txtCelTresKeyPressed

    private void cmbInstrucaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbInstrucaoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        txtCPF.requestFocus();
    }
    }//GEN-LAST:event_cmbInstrucaoKeyPressed

    private void cmbEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbEstadoCivilKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        cmbInstrucao.requestFocus();
    }
    }//GEN-LAST:event_cmbEstadoCivilKeyPressed

    private void txtCelTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelTresActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtCelTresActionPerformed

    private void txtCelDoisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelDoisFocusLost
    if(txtCelDois.getText().equals("(  )       -    "))
    {
        txtCelDois.setValue("");
    }
    }//GEN-LAST:event_txtCelDoisFocusLost

    private void txtCelTresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelTresFocusLost
    if(txtCelTres.getText().equals("(  )       -    "))
    {
        txtCelTres.setValue("");
    }
    }//GEN-LAST:event_txtCelTresFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadastrarFuncionario dialog = new frmCadastrarFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbInstrucao;
    private javax.swing.JComboBox<String> cmbSr;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCNH;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelDois;
    private javax.swing.JLabel lblCelTres;
    private javax.swing.JLabel lblCelUm;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataAdmissao;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblExpedicao;
    private javax.swing.JLabel lblFuncaoGratificada;
    private javax.swing.JLabel lblInstrucao;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblSr;
    private javax.swing.JLabel lblTituloEleitor;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNH;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtCelDois;
    private javax.swing.JFormattedTextField txtCelTres;
    private javax.swing.JFormattedTextField txtCelUm;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtDataAdmissao;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtExpedicao;
    private javax.swing.JTextField txtFuncaoGratificada;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTituloEleitor;
    // End of variables declaration//GEN-END:variables
 
}
