/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import Modelo.CadastrarUsuarioControle;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author miche
 */
public class frmCadastrarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form frmCadastrarUsuario
     */
    public frmCadastrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblErroUsuario.setVisible(false);
        lblErroSenha.setVisible(false);
        lblErroContraSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtCadastroUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblContraSenha = new javax.swing.JLabel();
        pwSenha = new javax.swing.JPasswordField();
        pwContraSenha = new javax.swing.JPasswordField();
        lblUsuario1 = new javax.swing.JLabel();
        lblErroUsuario = new javax.swing.JLabel();
        lblErroSenha = new javax.swing.JLabel();
        lblErroContraSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuário");
        setResizable(false);

        lblUsuario.setText("Usuário: ");

        lblSenha.setText("Senha:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblContraSenha.setText("Contra Senha:");

        lblUsuario1.setText("CADASTRAR NOVO USUÁRIO");

        lblErroUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblErroUsuario.setText("Insira um nome de usuário.");

        lblErroSenha.setForeground(new java.awt.Color(255, 0, 0));
        lblErroSenha.setText("Senha inválida.");

        lblErroContraSenha.setForeground(new java.awt.Color(255, 0, 0));
        lblErroContraSenha.setText("Contra senha inválida.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblUsuario1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblErroUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblUsuario)
                        .addGap(6, 6, 6)
                        .addComponent(txtCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblErroSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblSenha)
                        .addGap(6, 6, 6)
                        .addComponent(pwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblErroContraSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblContraSenha)
                        .addGap(18, 18, 18)
                        .addComponent(pwContraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnCadastrar)
                .addGap(50, 50, 50)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblUsuario1)
                .addGap(21, 21, 21)
                .addComponent(lblErroUsuario)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblUsuario))
                    .addComponent(txtCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblErroSenha)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblSenha))
                    .addComponent(pwSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErroContraSenha)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblContraSenha))
                    .addComponent(pwContraSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnSair))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String senha = new String(pwSenha.getPassword());
        String contraSenha = new String(pwContraSenha.getPassword());
        CadastrarUsuarioControle controle = new CadastrarUsuarioControle(txtCadastroUsuario.getText(), senha, contraSenha);
        
        if(controle.getMensagem().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
            lblErroUsuario.setVisible(false);
            lblErroSenha.setVisible(false);
            lblErroContraSenha.setVisible(false);
            txtCadastroUsuario.setText("");
            pwSenha.setText("");
            pwContraSenha.setText("");
            
        }
        
        if(controle.getMensagem().equals("erro 0"))
        {
            JOptionPane.showMessageDialog(null, "Depela 0");
            lblErroUsuario.setVisible(false);
            lblErroSenha.setVisible(false);
            lblErroContraSenha.setVisible(false);
        }
        
        if(controle.getMensagem().equals("erro 1"))
        {
            JOptionPane.showMessageDialog(null, "Depela 1");
            lblErroUsuario.setVisible(true);
            lblErroSenha.setVisible(false);
            lblErroContraSenha.setVisible(false);
        }
               
        if(controle.getMensagem().equals("erro 2"))
        {
            JOptionPane.showMessageDialog(null, "Depela 2");
            lblErroUsuario.setVisible(false);
            lblErroSenha.setVisible(true);
            lblErroContraSenha.setVisible(false);
        }
        if(controle.getMensagem().equals("erro 3"))
        {
            JOptionPane.showMessageDialog(null, "Depela 3");
            lblErroUsuario.setVisible(false);
            lblErroSenha.setVisible(false);
            lblErroContraSenha.setVisible(true);
        }
        
        if(controle.getMensagem().equals("erro 4"))
        {
            JOptionPane.showMessageDialog(null, "Depela 4");
            lblErroUsuario.setVisible(false);
            lblErroSenha.setVisible(true);
            lblErroContraSenha.setVisible(true);
        }
        
        if(controle.getMensagem().equals("erro 5"))
        {
            JOptionPane.showMessageDialog(null, "Depela 4");
            lblErroUsuario.setVisible(true);
            lblErroSenha.setVisible(false);
            lblErroContraSenha.setVisible(true);
        }
        
         if(controle.getMensagem().equals("erro 6"))
        {
            JOptionPane.showMessageDialog(null, "Depela 6");
            lblErroUsuario.setVisible(true);
            lblErroSenha.setVisible(true);
            lblErroContraSenha.setVisible(true);
        }
         
         if(controle.getMensagem().equals("erro 7"))
        {
            JOptionPane.showMessageDialog(null, "Depela 7");
            lblErroUsuario.setVisible(true);
            lblErroSenha.setVisible(true);
            lblErroContraSenha.setVisible(false);
        }
         
         if(controle.getMensagem().equals("erro 8"))
         {
            lblErroSenha.setVisible(true);
            lblErroContraSenha.setVisible(true);
         }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadastrarUsuario dialog = new frmCadastrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblContraSenha;
    private javax.swing.JLabel lblErroContraSenha;
    private javax.swing.JLabel lblErroSenha;
    private javax.swing.JLabel lblErroUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPasswordField pwContraSenha;
    private javax.swing.JPasswordField pwSenha;
    private javax.swing.JTextField txtCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
