/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import DTO.CadastrarFundamentoDTO;
import Modelo.ControleCadastrarFundamento;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miche
 */
public class frmPesquisador extends javax.swing.JDialog
{

    /**
     * Creates new form frmPesquisarFundamento1
     */
    public frmPesquisador(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        gerenciadorDeTabelas(tbPesquisar);
        gerenciadorDeTabelas(tbPesquisar);
        btnPesquisarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblPesquisarPor = new javax.swing.JLabel();
        cmbModoDePesquisa = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPesquisar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Ato Legal");

        lblPesquisarPor.setText("Pesquisa por:");

        cmbModoDePesquisa.setMaximumRowCount(3);
        cmbModoDePesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número", "Ano", "Data", "Ementa", "Ato", "Quantidade" }));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPesquisarActionPerformed(evt);
            }
        });

        tbPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Número", "Ano", "Data", "Ementa", "Ato", "Quantidade"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tbPesquisar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbPesquisar);
        if (tbPesquisar.getColumnModel().getColumnCount() > 0)
        {
            tbPesquisar.getColumnModel().getColumn(0).setResizable(false);
            tbPesquisar.getColumnModel().getColumn(1).setResizable(false);
            tbPesquisar.getColumnModel().getColumn(2).setResizable(false);
            tbPesquisar.getColumnModel().getColumn(3).setResizable(false);
            tbPesquisar.getColumnModel().getColumn(4).setResizable(false);
            tbPesquisar.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbModoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesquisarPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPesquisarPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbModoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPesquisarActionPerformed
    {//GEN-HEADEREND:event_btnPesquisarActionPerformed
        ControleCadastrarFundamento controle = new ControleCadastrarFundamento();
        List<CadastrarFundamentoDTO> lista;
        lista = controle.pesquisarAtoLegal();

        String[] colunas =
        {
            "Número", "Ano", "Data", "Ementa", "Ato", "Quantidade"
        };

        // O método isCellEditable é sobrescrito para retornar false, desabilitando a edição de todas as células da tabela.
        DefaultTableModel model = new DefaultTableModel(colunas, 0)
        {
            @Override
            public boolean isCellEditable(int rowIndex, int vColIndex)
            {
                return false;
            }
        };

        for (int i = 0; i < lista.size(); i++)
        {
            Object[] rowdata =
            {
                lista.get(i).getNumeroDaLei(), lista.get(i).getAnoDaLei(), lista.get(i).getDataDaLei(), lista.get(i).getEmentaDaLei(), lista.get(i).getAtoDaLei(), lista.get(i).getQtdVagasDaLei()
            };
            model.addRow(rowdata);
        }
        tbPesquisar.setModel(model);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    public void gerenciadorDeTabelas(JTable table)
    {
        DefaultTableCellRenderer centralizarCelulas = new DefaultTableCellRenderer();
        centralizarCelulas.setHorizontalAlignment(SwingConstants.CENTER);
        table.getTableHeader().setReorderingAllowed(false);
        for (int i = 0; i < table.getColumnCount(); i++)
        {
            table.getColumnModel().getColumn(i).setResizable(false);
            table.getColumnModel().getColumn(i).setCellRenderer(centralizarCelulas);
        }
    }

    public void tratarDadosSelecionados(Consumer<List<CadastrarFundamentoDTO>> callback)
    {
        obterSelecaoDaPesquisa(callback);
    }

    public void obterSelecaoDaPesquisa(Consumer<List<CadastrarFundamentoDTO>> callback)
    {

        tbPesquisar.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {

                int linhaSelecionada = tbPesquisar.getSelectedRow();

                if (linhaSelecionada != -1)
                {
                    CadastrarFundamentoDTO dto = new CadastrarFundamentoDTO();
                    //numero da lei
                    dto.setNumeroDaLei(tbPesquisar.getValueAt(linhaSelecionada, 0).toString());
                    //ano da lei
                    dto.setAnoDaLei(tbPesquisar.getValueAt(linhaSelecionada, 1).toString());
                    //data da lei      
                    dto.setDataDaLei(tbPesquisar.getValueAt(linhaSelecionada, 2).toString());
                    //ementa da lei 
                    dto.setEmentaDaLei(tbPesquisar.getValueAt(linhaSelecionada, 3).toString());
                    //ato da lei 
                    dto.setTipoAto(tbPesquisar.getValueAt(linhaSelecionada, 4).toString());
                    //Quantidade de vagas 
                    dto.setQtdVagasDaLei(tbPesquisar.getValueAt(linhaSelecionada, 5).toString());

                    List<CadastrarFundamentoDTO> lista = new ArrayList<>();

                    lista.add(dto);

                    callback.accept(lista);

                    dispose();
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPesquisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPesquisador dialog = new frmPesquisador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbModoDePesquisa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JTable tbPesquisar;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
