/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import DAO.ConversorClassificacao;
import DAO.Extenso;
import Modelo.PortariaDeNomeacaoControle;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageMar;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTSectPr;


/**
 *
 * @author miche
 */
public class frmPortariaDeNomeacao extends javax.swing.JDialog {

    frmPesquisarFuncionario frmPF = new frmPesquisarFuncionario(null, true);
    /**
     * Creates new form frmNomeacao
     */
    public frmPortariaDeNomeacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar2 = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        lblPortariaDeNomeacao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDataAdmissao = new javax.swing.JTextField();
        lblNumeroPortaria = new javax.swing.JLabel();
        lblCargoEmprego = new javax.swing.JLabel();
        txtCargoEmprego = new javax.swing.JTextField();
        lblNomeServidor = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        btnGerarPortaria = new javax.swing.JButton();
        lblAdmissao = new javax.swing.JLabel();
        btnVincularServidor = new javax.swing.JButton();
        lblMatricula = new javax.swing.JLabel();
        txtNomeServidor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtNumeroDaPortaria = new javax.swing.JFormattedTextField();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Portaria de Nomeação");

        lblPortariaDeNomeacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPortariaDeNomeacao.setText("PORTARIA DE NOMEAÇÃO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPortariaDeNomeacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPortariaDeNomeacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        txtDataAdmissao.setEnabled(false);

        lblNumeroPortaria.setText("N.º da Portaria:");

        lblCargoEmprego.setText("Cargo/Emprego: ");

        txtCargoEmprego.setEnabled(false);

        lblNomeServidor.setText("Nome Servidor: ");

        txtMatricula.setEnabled(false);

        btnGerarPortaria.setText("Gerar");
        btnGerarPortaria.setEnabled(false);
        btnGerarPortaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPortariaActionPerformed(evt);
            }
        });
        btnGerarPortaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGerarPortariaKeyPressed(evt);
            }
        });

        lblAdmissao.setText("Data de Admissão:");

        btnVincularServidor.setText("Vincular Servidor");
        btnVincularServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularServidorActionPerformed(evt);
            }
        });

        lblMatricula.setText("Matricula:");

        txtNomeServidor.setEnabled(false);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            txtNumeroDaPortaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumeroDaPortaria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroDaPortariaFocusLost(evt);
            }
        });
        txtNumeroDaPortaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDaPortariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVincularServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdmissao)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataAdmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumeroPortaria)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNomeServidor)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblCargoEmprego))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeServidor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargoEmprego)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(btnGerarPortaria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(55, 55, 55))
                                    .addComponent(txtNumeroDaPortaria, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMatricula))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVincularServidor)
                        .addComponent(lblAdmissao)
                        .addComponent(txtDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeServidor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargoEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCargoEmprego))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroPortaria)
                            .addComponent(txtNumeroDaPortaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnGerarPortaria)))
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarPortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPortariaActionPerformed
       
        PortariaDeNomeacaoControle controle = new PortariaDeNomeacaoControle(txtMatricula.getText(), txtDataAdmissao.getText(), txtNomeServidor.getText(), txtCargoEmprego.getText(), txtNumeroDaPortaria.getText());
        if(controle.getMensagem().equals("ok"))
        {
            btnGerarPortaria();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Preencha todas as informações antes de continuar.");
        }
    }//GEN-LAST:event_btnGerarPortariaActionPerformed
    private void btnGerarPortaria()
    {
        ConversorClassificacao conversorClassificacao = new ConversorClassificacao();
        
        
        //BOTÃO GERAR PORTARIA
        FileOutputStream fileOutPut = null;
        
        //cria o documento
        XWPFDocument document = new XWPFDocument();
        
        //configuração da margem para 5,5(margem sup) + 3 (margem inferior) + 3 (margem esquerda) + 2 (margem direita)
        CTSectPr sectPr = document.getDocument().getBody().addNewSectPr();
        CTPageMar pageMar = sectPr.addNewPgMar();
        pageMar.setTop(BigInteger.valueOf(3120L));
        pageMar.setBottom(BigInteger.valueOf(1703L));
        pageMar.setLeft(BigInteger.valueOf(1703L));
        pageMar.setRight(BigInteger.valueOf(1135L));
            
        try
        {
            //diretório que será criado com o arquivo da portaria
            String diretorio = "C:/modelos/";
            String nomeDoArquivo = "Portaria de Nomeação.docx";
            String fontTimesNewRoman = "Times New Roman";
            //caso não exista o diretorio, crie um e salve
            File f = new File(diretorio);
            if(!f.exists())
            {
                System.out.println("Diretório criado " + diretorio);
                f.mkdirs();
            }
            
            //cria I/O
            fileOutPut = new FileOutputStream(new File(diretorio + nomeDoArquivo));
     
            //cria o paragrafo
            XWPFParagraph paragrafo1 = document.createParagraph();
            paragrafo1.setAlignment(ParagraphAlignment.CENTER);
            paragrafo1.setSpacingAfter(0);
            XWPFRun p1 = paragrafo1.createRun();
            
            p1.setText("PORTARIA Nº " + txtNumeroDaPortaria.getText());
            p1.setFontSize(12);
            p1.setFontFamily(fontTimesNewRoman);
            p1.setBold(true);
            p1.addCarriageReturn();
            
            SimpleDateFormat sdfDia = new SimpleDateFormat("d");
            String dia = sdfDia.format(jCalendar1.getDate());
            
            SimpleDateFormat sdfMes = new SimpleDateFormat("M");
            String mes = sdfMes.format(jCalendar1.getDate());
            
            SimpleDateFormat sdfAno = new SimpleDateFormat("yyyy");
            String ano = sdfAno.format(jCalendar1.getDate());
            
            String mesPorExtenso[] = {"janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"};
            String mesNumeral[] = {"1","2","3","4","5","6","7","8","9","10","11","12"};
            
            for(int i = 1; i < 12; i++)
            {
                if(mes.equals(mesNumeral[i]))
                {
                    mes = mesPorExtenso[i];
                }
            }
            
            p1.setText("De "+dia+" de "+mes+" de "+ano+".");
            p1.setBold(true);
            p1.addCarriageReturn();
            p1.addCarriageReturn();
            
            XWPFParagraph paragrafo2 = document.createParagraph();
            
            paragrafo2.setAlignment(ParagraphAlignment.BOTH);
            //recuo a esquerda em 6 cm
            paragrafo2.setIndentFromLeft(3400);
            //espaçamento antes
            paragrafo2.setSpacingAfter(0);
            //espaçamento entre linhas simples
            paragrafo2.setSpacingBetween(1);
            XWPFRun p2 = paragrafo2.createRun();         
            p2.setFontSize(12);
            p2.setFontFamily(fontTimesNewRoman);
            p2.setText((frmPF.getLista().get(frmPF.getIndex()).getRegimeJuridico().equals("CLT")) ? "“Dispõe sobre a nomeação de empregado público municipal e dá outras providências.”" : "“Dispõe sobre a nomeação de ocupante de cargo de provimento em comissão e dá outras providências.”");
            p2.setBold(true);
            p2.addCarriageReturn();
            
            //segundo paragrafo
            XWPFParagraph paragrafo3 = document.createParagraph();
            paragrafo3.setAlignment(ParagraphAlignment.BOTH);
            //primeira linha por 6 cm
            paragrafo3.setIndentationFirstLine(3400);            
            //espaçamento antes
            paragrafo3.setSpacingAfter(0);
            //espaçamento entre linhas simples
            paragrafo3.setSpacingBetween(1);
            XWPFRun p3 = paragrafo3.createRun();         
            p3.setFontSize(12);
            p3.setFontFamily(fontTimesNewRoman);
            p3.setText("A Prefeita do Município de Quadra, Estado de São Paulo, no uso de suas atribuições legais, expede a seguinte");
           
            XWPFRun portaria4 = paragrafo3.createRun(); 
            portaria4.setFontSize(12);
            portaria4.setFontFamily(fontTimesNewRoman);
            portaria4.setText(" PORTARIA: ");
            portaria4.setBold(true);     
            portaria4.addCarriageReturn();
            
            //artigo 1º
            XWPFParagraph paragrafo4 = document.createParagraph();
            paragrafo4.setAlignment(ParagraphAlignment.BOTH);
            paragrafo4.setIndentationFirstLine(3400);            
            paragrafo4.setSpacingAfter(0);
            paragrafo4.setSpacingBetween(1);
            
            XWPFRun artigoPrimeiro = paragrafo4.createRun(); 
            artigoPrimeiro.setFontSize(12);
            artigoPrimeiro.setFontFamily(fontTimesNewRoman);
            artigoPrimeiro.setText("Art. 1º - ");
            artigoPrimeiro.setBold(true);   
   
            
            XWPFRun p4 = paragrafo4.createRun();         
            p4.setFontSize(12);
            p4.setFontFamily(fontTimesNewRoman);
            p4.setText("Fica " + (frmPF.getLista().get(frmPF.getIndex()).getPronomeTratamento().equals("SR.") ? " nomeado " : " nomeada ") + " para exercer o " + (frmPF.getLista().get(frmPF.getIndex()).getRegimeJuridico().equals("CLT") ? " emprego público " : " cargo ") + " de " + frmPF.getLista().get(frmPF.getIndex()).getCargo() + ", referência " + frmPF.getLista().get(frmPF.getIndex()).getReferencia() + " da escala de vencimentos vigente, " + (frmPF.getLista().get(frmPF.getIndex()).getPronomeTratamento().equals("SR.") ? " o Sr.  " : " a Sra. ") + (frmPF.getLista().get(frmPF.getIndex()).getNome())+ "," + (frmPF.getLista().get(frmPF.getIndex()).getPronomeTratamento().equals("SR.") ? " aprovado " : " aprovada ") + " no concurso público n.º " + frmPF.getLista().get(frmPF.getIndex()).getNumeroConcurso() + ", " + frmPF.getLista().get(frmPF.getIndex()).getClassificacaoConcurso() + "ª ("+conversorClassificacao.ConverterClassificacao(Integer.parseInt(frmPF.getLista().get(frmPF.getIndex()).getClassificacaoConcurso()))+")" + " classificação," + " brasileiro, " + frmPF.getLista().get(frmPF.getIndex()).getEstadoCivil() + ", portador da cédula de identidade RG n.º: 48.497.501 SSP/SP e inscrito no CPF/MF n.º: 400.942.118-50, com as atribuições constantes na Lei Municipal nº 166 de 14 de maio de 2002 e remuneração constante no Anexo IV da Lei nº 722/2020 atualizado pela Lei 835/2022.");
            p4.addCarriageReturn();
            
            //artigo 2º
            XWPFParagraph paragrafo5 = document.createParagraph();
            paragrafo5.setAlignment(ParagraphAlignment.BOTH);
            paragrafo5.setIndentationFirstLine(3400);            
            paragrafo5.setSpacingAfter(0);
            paragrafo5.setSpacingBetween(1);
            
            XWPFRun artigoSegundo = paragrafo5.createRun(); 
            artigoSegundo.setFontSize(12);
            artigoSegundo.setFontFamily(fontTimesNewRoman);
            artigoSegundo.setText("Art. 2º - ");
            artigoSegundo.setBold(true);   
            
            XWPFRun p5 = paragrafo5.createRun();         
            p5.setFontSize(12);
            p5.setFontFamily(fontTimesNewRoman);
            p5.setText("O servidor ora nomeado prestará compromisso de posse em termo próprio e individual e apresentará a declaração de bens, na forma do Art. 43, da Lei Orgânica do Município.");
            p5.addCarriageReturn();
            
            //artigo 3º
            XWPFParagraph paragrafo6 = document.createParagraph();
            paragrafo6.setAlignment(ParagraphAlignment.BOTH);
            paragrafo6.setIndentationFirstLine(3400);            
            paragrafo6.setSpacingAfter(0);
            paragrafo6.setSpacingBetween(1);
            
            XWPFRun artigoTerceiro = paragrafo6.createRun(); 
            artigoTerceiro.setFontSize(12);
            artigoTerceiro.setFontFamily(fontTimesNewRoman);
            artigoTerceiro.setText("Art. 3º - ");
            artigoTerceiro.setBold(true);   
            
            XWPFRun p6 = paragrafo6.createRun();         
            p6.setFontSize(12);
            p6.setFontFamily(fontTimesNewRoman);
            p6.setText("As despesas decorrentes desta Portaria correrão por conta de dotação consignada no orçamento vigente, suplementada se necessário.");
            p6.addCarriageReturn();     
            
            //artigo 4º
            XWPFParagraph paragrafo7 = document.createParagraph();
            paragrafo7.setAlignment(ParagraphAlignment.BOTH);
            paragrafo7.setIndentationFirstLine(3400);            
            paragrafo7.setSpacingAfter(0);
            paragrafo7.setSpacingBetween(1);
            
            XWPFRun artigoQuarto = paragrafo7.createRun(); 
            artigoQuarto.setFontSize(12);
            artigoQuarto.setFontFamily(fontTimesNewRoman);
            artigoQuarto.setText("Art. 4º - ");
            artigoQuarto.setBold(true);   
            
            XWPFRun p7 = paragrafo7.createRun();         
            p7.setFontSize(12);
            p7.setFontFamily(fontTimesNewRoman);
            p7.setText("Esta Portaria entra em vigor na data de sua publicação, revogadas as disposições contrárias.");
            p7.addCarriageReturn();    
            
            //dataº
            XWPFParagraph paragrafo8 = document.createParagraph();
            paragrafo8.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo8.setSpacingAfter(0);
            XWPFRun p8 = paragrafo8.createRun();         
            p8.setFontSize(12);
            p8.setFontFamily(fontTimesNewRoman);
            p8.setText("Quadra/SP, 18 de julho de 2022");
            p8.addCarriageReturn();
            p8.addCarriageReturn();
            
            //nome prefeito
            XWPFParagraph paragrafo9 = document.createParagraph();
            paragrafo9.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo9.setSpacingAfter(0);
            XWPFRun p9 = paragrafo9.createRun();         
            p9.setFontSize(12);
            p9.setFontFamily(fontTimesNewRoman);
            p9.setText("LHEONIDES DE OLIVEIRA ANDRADE");
            p9.addCarriageReturn();
            p9.setText("PREFEITA MUNICIPAL");
            p9.setBold(true);
            p9.addCarriageReturn(); 
            
            //registrado em livros proprios
            XWPFParagraph paragrafo10 = document.createParagraph();
            paragrafo10.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo10.setSpacingAfter(0);
            XWPFRun p10 = paragrafo10.createRun();         
            p10.setFontSize(12);
            p10.setFontFamily(fontTimesNewRoman);
            p10.setText("Registrada em livros próprios e afixada no átrio do paço municipal na data supra.");
            p10.addCarriageReturn(); 
            p10.addCarriageReturn(); 
            
            //nome de quem faz a portaria
            XWPFParagraph paragrafo11 = document.createParagraph();
            paragrafo11.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo11.setSpacingAfter(0);
            XWPFRun p11 = paragrafo11.createRun();         
            p11.setFontSize(12);
            p11.setFontFamily(fontTimesNewRoman);
            p11.setText("ALESANDRA MASCARENHA MENDES");
            p11.addCarriageReturn();
            p11.setText("ASSISTENTE ADMINISTRATIVO");
            p11.setBold(true);
            p11.addCarriageReturn();
            
            //nome de quem faz a portaria
            XWPFParagraph paragrafo12 = document.createParagraph();
            paragrafo12.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo12.setSpacingAfter(0);
            XWPFRun p12 = paragrafo12.createRun();         
            p12.setFontSize(12);
            p12.setFontFamily(fontTimesNewRoman);
            p12.setText("TERMO DE COMPROMISSO E POSSE");
            p12.addCarriageReturn();
            p12.setBold(true);
            for(int i =0; i<3; i++)
            {
                p12.addCarriageReturn();
            }
            
            //termo de compromisso e posse
            XWPFParagraph paragrafo13 = document.createParagraph();
            paragrafo13.setAlignment(ParagraphAlignment.BOTH); 
            paragrafo13.setIndentationFirstLine(1983); 
            paragrafo13.setSpacingBetween(1.5);
            paragrafo13.setSpacingAfter(0);
            XWPFRun p13 = paragrafo13.createRun();         
            p13.setFontSize(12);
            p13.setFontFamily(fontTimesNewRoman);
            p13.setText("Aos dezoito (18) dias do mês de julho do ano de 2022, nesta cidade de Quadra, Estado de São Paulo, às 09 horas, no Gabinete da Prefeita, onde presente se encontrava a Exmª Sra. LHEONIDES DE OLIVEIRA ANDRADE, DD. Prefeita Municipal, compareceu o Sr. CLEVIO LOBO, portador da cédula de identidade RG nº 48.497.501 SSP/SP e inscrito no CPF/MF nº 400.942.118-50, e pelo mesmo foi manifestado expressa disposição em tomar posse no emprego público de AJUDANTE GERAL, para qual foi nomeado através da Portaria nº 143/2022 de 18 de julho de 2022, prometendo  exercer com zelo, dedicação e lealdade, sem dolo nem malícia, as atribuições do referido emprego público. Diante do compromisso prestado e tendo o servidor nomeado apresentado a sua Declaração de Bens, a Sra. Prefeita Municipal declarou-o empossado, na forma da Lei. Para constar, lavrei o presente termo que lido e achado conforme vai devidamente assinado. Eu ___________________ (Alessandra Mascarenha Mendes), Assistente Administrativo, digitei, conferi e subscrevo.");
            p13.addCarriageReturn();
            p13.addCarriageReturn(); 
            p13.addCarriageReturn(); 
            
            //nome prefeito
            XWPFParagraph paragrafo14 = document.createParagraph();
            paragrafo14.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo14.setSpacingAfter(0);
            XWPFRun p14 = paragrafo14.createRun();         
            p14.setFontSize(12);
            p14.setFontFamily(fontTimesNewRoman);
            p14.setText("LHEONIDES DE OLIVEIRA ANDRADE");
            p14.addCarriageReturn(); 
            p14.setText("PREFEITA MUNICIPAL");
            p14.setBold(true);
            p14.addCarriageReturn(); 
            p14.addCarriageReturn();
            p14.addCarriageReturn(); 
            p14.addCarriageReturn(); 

            //nome do funcionario
            XWPFParagraph paragrafo15 = document.createParagraph();
            paragrafo15.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo15.setSpacingAfter(0);
            XWPFRun p15 = paragrafo15.createRun();         
            p15.setFontSize(12);
            p15.setFontFamily(fontTimesNewRoman);
            p15.setText("CLEVIO LOBO");
            p15.addCarriageReturn();
            p15.setText("FUNCIONÁRIO PÚBLICO MUNICIPAL");
            p15.setBold(true);
            p15.addCarriageReturn();
            p15.addCarriageReturn();
            p15.addCarriageReturn();
            
            //termo de ciencia e notificação
            XWPFParagraph paragrafo16 = document.createParagraph();
            paragrafo16.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo16.setSpacingAfter(0);
            XWPFRun p16 = paragrafo16.createRun();         
            p16.setFontSize(12);
            p16.setFontFamily(fontTimesNewRoman);
            p16.setText("ANEXO AP - 01 - TERMO DE CIÊNCIA E DE NOTIFICAÇÃO");
            p16.addCarriageReturn();
            p16.setText("(ATOS DE PESSOAL)");
            p16.setBold(true);
            p16.addCarriageReturn();
            
            //termo de ciencia e notificação - descrição
            XWPFParagraph paragrafo17 = document.createParagraph();
            paragrafo17.setAlignment(ParagraphAlignment.LEFT); 
            paragrafo17.setSpacingAfter(0);
            XWPFRun p17 = paragrafo17.createRun();         
            p17.setFontSize(12);
            p17.setFontFamily(fontTimesNewRoman);
            p17.setFontSize(12);
            p17.setFontFamily(fontTimesNewRoman);
            p17.setText("ÓRGÃO OU ENTIDADE: PREFEITURA MUNICIPAL DE QUADRA");
            p17.addCarriageReturn();
            p17.setText("PROCESSO Nº (DE ORIGEM): -");
            p17.addCarriageReturn();
            p17.setText("GESTOR DO ÓRGÃO/ENTIDADE: LHEONIDES DE OLIVEIRA ANDRADE");
            p17.addCarriageReturn();
            p17.setText("RESPONSÁVEL PELO ATO: LHEONIDES DE OLIVEIRA ANDRADE");
            p17.addCarriageReturn();
            p17.setText("INTERESSADO(A): CLEVIO LOBO");
            p17.addCarriageReturn();
            p17.setText("ADVOGADO/Nº OAB / E-MAIL: EMERSON CARESIA / OABSP Nº 265.833/ E-MAIL: advocacia@quadra.sp.gov.br");
            p17.addCarriageReturn();
            p17.addCarriageReturn();
            p17.setText("Pelo presente TERMO, nós, abaixo identificados:");
            p17.addCarriageReturn();
            
            //estamos cientes de que
            XWPFParagraph paragrafo18 = document.createParagraph();
            paragrafo18.setAlignment(ParagraphAlignment.LEFT); 
            paragrafo18.setSpacingAfter(0);
            XWPFRun p18 = paragrafo18.createRun();     
            p18.setFontSize(12);
            p18.setFontFamily(fontTimesNewRoman);
            p18.setText("2. Estamos CIENTES de que:");
            p18.setBold(true);
            
            //termo de ciencia e notificação - descrição
            XWPFParagraph paragrafo19 = document.createParagraph();
            paragrafo19.setAlignment(ParagraphAlignment.BOTH); 
            paragrafo19.setSpacingAfter(0);
            XWPFRun p19 = paragrafo19.createRun();   
            p19.setFontSize(12);
            p19.setFontFamily(fontTimesNewRoman);

            p19.addCarriageReturn();
            p19.setText("a) O ato acima referido, objetivando seu registro pelo Tribunal de Contas do Estado de São Paulo, será objeto de prévia análise, cujo trâmite processual ocorrerá pelo sistema eletrônico;\n");
            p19.addCarriageReturn();
            p19.setText("\nb) Poderemos ter acesso ao processo, tendo vista e extraindo cópias das manifestações de interesse, Despachos e Decisões, cabendo, para tanto, procedermos ao regular cadastramento no Sistema de Processo Eletrônico, na conformidade do quanto estabelece a Resolução nº 01/2011 do TCESP;\n");
            p19.addCarriageReturn();
            p19.setText("\nc) Além de disponíveis no processo eletrônico, todos os Despachos e Decisões que vierem a ser tomados, relativamente ao aludido processo, serão publicados no Diário Oficial do Estado, Caderno do Poder Legislativo, parte do Tribunal de Contas do Estado de São Paulo, em conformidade com o artigo 90 da Lei Complementar nº 709, de 14 de janeiro de 1993, iniciando-se, a partir de então, a contagem dos prazos processuais, conforme regras do Código de Processo Civil;\n"); 
            p19.addCarriageReturn();
            p19.setText("\nd) Qualquer alteração de endereço – residencial ou eletrônico – ou telefones de contato deverá ser comunicada pelo interessado, peticionando no processo.");
            p19.addCarriageReturn();
            
            //damo-nos por notificados
            XWPFParagraph paragrafo20 = document.createParagraph();
            paragrafo20.setAlignment(ParagraphAlignment.LEFT); 
            paragrafo20.setSpacingAfter(0);
            XWPFRun p20 = paragrafo20.createRun();     
            p20.setFontSize(12);
            p20.setFontFamily(fontTimesNewRoman);
            p20.setText("2. Damo-nos por NOTIFICADOS para:");
            p20.setBold(true);
            p20.addCarriageReturn();
            
            XWPFParagraph paragrafo21 = document.createParagraph();
            paragrafo21.setAlignment(ParagraphAlignment.BOTH); 
            paragrafo21.setSpacingAfter(0);
            XWPFRun p21 = paragrafo21.createRun(); 
            p21.setFontSize(12);
            p21.setFontFamily(fontTimesNewRoman);
            p21.setText("a) O ato acima referido, objetivando seu registro pelo Tribunal de Contas do Estado de São Paulo, será objeto de prévia análise, cujo trâmite processual ocorrerá pelo sistema eletrônico;\n");
            p21.addCarriageReturn();
            p21.setText("\nb) Se for o caso e de nosso interesse, nos prazos e nas formas legais e regimentais, exercer o direito de defesa, interpor recursos e o que mais couber.");
            p21.addCarriageReturn();
            p21.addCarriageReturn();
            
            //damo-nos por notificados
            XWPFParagraph paragrafo22 = document.createParagraph();
            paragrafo22.setAlignment(ParagraphAlignment.CENTER); 
            paragrafo22.setSpacingAfter(0);
            XWPFRun p22 = paragrafo22.createRun();     
            p22.setFontSize(12);
            p22.setFontFamily(fontTimesNewRoman);
            p22.setText("QUADRA/SP, 18 DE JULHO DE 2022.");
            p22.setBold(true);
            for(int i = 0; i < 3; i++)
            {
            p22.addCarriageReturn();
            }
            
            //informações do gestor do orgão
            XWPFParagraph paragrafo23 = document.createParagraph();
            paragrafo23.setAlignment(ParagraphAlignment.LEFT); 
            paragrafo23.setSpacingAfter(0);
            XWPFRun p23 = paragrafo23.createRun(); 
            p23.setFontSize(12);
            p23.setFontFamily(fontTimesNewRoman);
            p23.setText("GESTOR DO ÓRGÃO/ENTIDADE E RESPONSÁVEL PELO ATO");
            p23.addCarriageReturn();
            p23.addCarriageReturn();
            p23.setText("\nNome e cargo: LHEONIDES DE OLIVEIRA ANDRADE – PREFEITA MUNICIPAL.");
            p23.addCarriageReturn();
            p23.setText("\nCPF: 026.828.638-84 RG: 10.704.898-X.");
            p23.addCarriageReturn();
            p23.setText("\nData de Nascimento: 16/09/1958.");
            p23.addCarriageReturn();
            p23.setText("\nEndereço residencial completo: RUA JOÃO ANTONIO LOBO, 321, CENTRO, QUADRA/SP.");
            p23.addCarriageReturn();
            p23.setText("\nE-mail institucional: gabinete@quadra.sp.gov.br.");
            p23.addCarriageReturn();
            p23.setText("\nE-mail pessoal: lheonidesoliveira@hotmail.com.");
            p23.addCarriageReturn();
            p23.setText("\nTelefone(s): (15) 99683-8183");
            p23.addCarriageReturn();           
            p23.addCarriageReturn();
            p23.setText("\nAssinatura:_______________________________________________________");
            p23.setBold(true);
            p23.addCarriageReturn();           
            p23.addCarriageReturn();
            p23.addCarriageReturn();  
            p23.addCarriageReturn();
            p23.addCarriageReturn();
           
            //informações do gestor do orgão
            XWPFParagraph paragrafo24 = document.createParagraph();
            paragrafo24.setAlignment(ParagraphAlignment.LEFT); 
            paragrafo24.setSpacingAfter(0);
            XWPFRun p24 = paragrafo24.createRun(); 
            p24.setFontSize(12);
            p24.setFontFamily(fontTimesNewRoman);
            p24.setText("INTERESSADO(A)");
            p24.addCarriageReturn();
            p24.addCarriageReturn();
            p24.setText("\nNome e cargo: CLEVIO LOBO –AJUDANTE GERAL");
            p24.addCarriageReturn();
            p24.setText("\nCPF/MF nº: 400.942.118-50 RG: 48.497.501");
            p24.addCarriageReturn();
            p24.setText("\nData de Nascimento: 27/11/1992 ");
            p24.addCarriageReturn();
            p24.setText("\nEndereço residencial completo: JOSE BENEDITO DE JESUS MENDES, S/N, BAIRRO DOS VAZ, QUADRA/SP");
            p24.addCarriageReturn();
            p24.setText("\nE-mail pessoal: roselixavier09@gmail.com");
            p24.addCarriageReturn();
            p24.setText("\nTel.(s):  (15) 99826-6649");
            p24.addCarriageReturn();          
            p24.addCarriageReturn();
            p24.setText("\nAssinatura:_______________________________________________________");
            p24.setBold(true);
                   
            //escreve o documento dentro do sistema
            document.write(fileOutPut);
            
            //comando para fechar o arquivo e conseguir abrir sem fechar o sistema
            document.close();
            fileOutPut.close();
            JOptionPane.showMessageDialog(null, "Portaria gerada com sucesso!");
        }
        catch(FileNotFoundException ex)
        {
             JOptionPane.showMessageDialog(null, "Caiu aqui 2");
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(null, "Caiu aqui 2");
            Logger.getLogger(frmPortariaDeNomeacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnVincularServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularServidorActionPerformed
        frmPF.setVisible(true);
        if(frmPF.getMensagem().equals("pode passar"))
        {
            txtMatricula.setText(frmPF.getLista().get(frmPF.getIndex()).getMatricula());
            txtNomeServidor.setText(frmPF.getLista().get(frmPF.getIndex()).getNome());
            txtDataAdmissao.setText(frmPF.getLista().get(frmPF.getIndex()).getDataAdmissao());
            txtCargoEmprego.setText(frmPF.getLista().get(frmPF.getIndex()).getCargo());
        }
    }//GEN-LAST:event_btnVincularServidorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumeroDaPortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDaPortariaActionPerformed
      
        if(!txtNumeroDaPortaria.getText().equals("   /    "))
        {
            btnGerarPortaria.setEnabled(true);
            btnGerarPortaria.requestFocus();
        }
    }//GEN-LAST:event_txtNumeroDaPortariaActionPerformed

    private void btnGerarPortariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGerarPortariaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
           btnGerarPortaria(); 
        }
    }//GEN-LAST:event_btnGerarPortariaKeyPressed

    private void txtNumeroDaPortariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDaPortariaFocusLost
        if(!txtNumeroDaPortaria.getText().equals("   /    "))
        {
            btnGerarPortaria.setEnabled(true);
            btnGerarPortaria.requestFocus();
        }
    }//GEN-LAST:event_txtNumeroDaPortariaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPortariaDeNomeacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPortariaDeNomeacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPortariaDeNomeacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPortariaDeNomeacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPortariaDeNomeacao dialog = new frmPortariaDeNomeacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarPortaria;
    private javax.swing.JButton btnVincularServidor;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdmissao;
    private javax.swing.JLabel lblCargoEmprego;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNomeServidor;
    private javax.swing.JLabel lblNumeroPortaria;
    private javax.swing.JLabel lblPortariaDeNomeacao;
    private javax.swing.JTextField txtCargoEmprego;
    private javax.swing.JTextField txtDataAdmissao;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNomeServidor;
    private javax.swing.JFormattedTextField txtNumeroDaPortaria;
    // End of variables declaration//GEN-END:variables
}
