/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Apresentacao;

import DTO.ServidoresPesquisarFuncionarioDTO;
import Modelo.ServidoresCadastrarFuncionarioControle;
import com.sun.org.apache.xml.internal.utils.ObjectStack;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class frmServidores extends javax.swing.JDialog {

    boolean boolChkCargoEmComissao = false;
    /**
     * Creates new form frmManutencaoo
     */
    public frmServidores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtExpedicao.setText("SSP/SP");
        txtCidade.setText("QUADRA/SP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abaServidores = new javax.swing.JTabbedPane();
        pnDadosPessoais = new javax.swing.JPanel();
        lblCelDois = new javax.swing.JLabel();
        lblCelTres = new javax.swing.JLabel();
        txtTituloEleitor = new javax.swing.JTextField();
        lblTituloEleitor = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtDataAdmissao = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        lblCPF = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblNome = new javax.swing.JLabel();
        txtCelUm = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        txtCelDois = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtCelTres = new javax.swing.JFormattedTextField();
        txtEndereco = new javax.swing.JTextField();
        cmbInstrucao = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        lblCargoEmprego = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        txtCargo = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        lblExpedicao = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblDataAdmissao = new javax.swing.JLabel();
        lblReferencia = new javax.swing.JLabel();
        lblFuncaoGratificada = new javax.swing.JLabel();
        txtFuncaoGratificada = new javax.swing.JTextField();
        lblSr = new javax.swing.JLabel();
        cmbSr = new javax.swing.JComboBox<>();
        txtExpedicao = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        lblInstrucao = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        lblNaturalidade = new javax.swing.JLabel();
        txtCNH = new javax.swing.JTextField();
        lblCNH = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblCelUm = new javax.swing.JLabel();
        cmbQuemAssinaPortaria = new javax.swing.JComboBox<>();
        lblEmail1 = new javax.swing.JLabel();
        pnCargoEmprego = new javax.swing.JPanel();
        lblNumeroPortariaNomeacao = new javax.swing.JLabel();
        txtNumeroPortariaNomeacao = new javax.swing.JTextField();
        lblNumeroDoConcurso = new javax.swing.JLabel();
        txtNumeroDoConcurso = new javax.swing.JTextField();
        lblLeiAtribuicaoCargoEmprego = new javax.swing.JLabel();
        txtLeiAtribuicaoCargoEmprego = new javax.swing.JTextField();
        lblClassificacaoConcurso = new javax.swing.JLabel();
        txtClassificacaoConcurso = new javax.swing.JTextField();
        lblDataPortariaNomeacao = new javax.swing.JLabel();
        txtDataPortariaNomeacao = new javax.swing.JTextField();
        lblReajusteCargoEmprego = new javax.swing.JLabel();
        txtLeiReajusteCargoEmprego = new javax.swing.JTextField();
        lblRegimeJuridico = new javax.swing.JLabel();
        cmbRegimeJuridico = new javax.swing.JComboBox<>();
        chkCargoEmComissao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidores");
        setResizable(false);

        lblCelDois.setText("Cel 2");

        lblCelTres.setText("Cel 3");

        txtTituloEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloEleitorActionPerformed(evt);
            }
        });

        lblTituloEleitor.setText("Título de Eleitor");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/incluir.png"))); // NOI18N
        btnCadastrar.setToolTipText("Cadastrar Funcionário");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pesquisar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar Funcionários");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/alterar.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar Dados");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir Funcionários");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        try {
            txtDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataAdmissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataAdmissaoFocusLost(evt);
            }
        });
        txtDataAdmissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataAdmissaoKeyPressed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setToolTipText("");
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
        });

        lblCPF.setText("CPF:");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoFocusLost(evt);
            }
        });
        txtDataNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataNascimentoKeyPressed(evt);
            }
        });

        lblNome.setText("Nome:");

        try {
            txtCelUm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelUm.setText("   ");
        txtCelUm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelUmFocusLost(evt);
            }
        });
        txtCelUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelUmActionPerformed(evt);
            }
        });
        txtCelUm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelUmKeyPressed(evt);
            }
        });

        lblEndereco.setText("Endereço:");

        try {
            txtCelDois.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelDois.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelDoisFocusLost(evt);
            }
        });
        txtCelDois.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelDoisKeyPressed(evt);
            }
        });

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        try {
            txtCelTres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelTres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelTresFocusLost(evt);
            }
        });
        txtCelTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelTresActionPerformed(evt);
            }
        });
        txtCelTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelTresKeyPressed(evt);
            }
        });

        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        cmbInstrucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNDAMENTAL I - 1º AO 5º ANO - INCOMPLETO", "FUNDAMENTAL I - 1º AO 5º ANO - COMPLETO", "FUNDAMENTAL II -  6º AO 9º ANO - INCOMPLETO", "FUNDAMENTAL II -  6º AO 9º ANO - COMPLETO", "ENSINO MÉDIO - INCOMPLETO", "ENSINO MÉDIO - COMPLETO", "ENSINO TÉCNICO - INCOMPLETO", "ENSINO TÉCNICO - COMPLETO", "ENSINO SUPERIOR - INCOMPLETO", "ENSINO SUPERIOR - COMPLETO" }));
        cmbInstrucao.setSelectedIndex(5);
        cmbInstrucao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbInstrucaoKeyPressed(evt);
            }
        });

        lblNumero.setText("Número:");

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO", "CASADO", "SEPARADO", "DIRVOCIADO", "VIÚVO" }));
        cmbEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbEstadoCivilKeyPressed(evt);
            }
        });

        lblCargoEmprego.setText("Cargo/Emprego");

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBairroFocusLost(evt);
            }
        });
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        lblBairro.setText("Bairro:");

        lblMatricula.setText("Matrícula: ");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar.png"))); // NOI18N
        btnGravar.setToolTipText("Gravar Alteração.");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        txtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCargoFocusLost(evt);
            }
        });
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRGFocusLost(evt);
            }
        });
        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });

        lblRG.setText("RG:");

        txtReferencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReferenciaFocusLost(evt);
            }
        });
        txtReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaActionPerformed(evt);
            }
        });

        lblExpedicao.setText("Exp.:");

        lblDataNascimento.setText("Dt Nascimento");

        lblDataAdmissao.setText("Dt Admissão:");

        lblReferencia.setText("Referência");

        lblFuncaoGratificada.setText("Função Gratificada");

        txtFuncaoGratificada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFuncaoGratificadaFocusLost(evt);
            }
        });
        txtFuncaoGratificada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncaoGratificadaActionPerformed(evt);
            }
        });

        lblSr.setText("Sr.:");

        cmbSr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SR.", "SRA." }));
        cmbSr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSrActionPerformed(evt);
            }
        });

        txtExpedicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpedicaoFocusLost(evt);
            }
        });
        txtExpedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpedicaoActionPerformed(evt);
            }
        });

        lblEstadoCivil.setText("Estado Civil");

        lblInstrucao.setText("Instrução");

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        lblCidade.setText("Cidade:");

        txtNaturalidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNaturalidadeFocusLost(evt);
            }
        });
        txtNaturalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaturalidadeActionPerformed(evt);
            }
        });

        lblNaturalidade.setText("Naturalidade:");

        txtCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNHActionPerformed(evt);
            }
        });

        lblCNH.setText("CNH:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setText("E-mail:");

        lblCelUm.setText("Cel 1");

        cmbQuemAssinaPortaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO IRÁ ASSINAR PORTARIAS", "PREFEITO", "SECRETÁRIO OU CORRELATO DE CONFIANÇA" }));
        cmbQuemAssinaPortaria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbQuemAssinaPortariaFocusLost(evt);
            }
        });
        cmbQuemAssinaPortaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuemAssinaPortariaActionPerformed(evt);
            }
        });
        cmbQuemAssinaPortaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbQuemAssinaPortariaKeyPressed(evt);
            }
        });

        lblEmail1.setText("Para compor assinaturas das Portarias");

        javax.swing.GroupLayout pnDadosPessoaisLayout = new javax.swing.GroupLayout(pnDadosPessoais);
        pnDadosPessoais.setLayout(pnDadosPessoaisLayout);
        pnDadosPessoaisLayout.setHorizontalGroup(
            pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtCelUm, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtCelDois, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtCelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnGravar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargoEmprego)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFuncaoGratificada)
                            .addComponent(txtFuncaoGratificada, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail1)
                            .addComponent(cmbQuemAssinaPortaria, 0, 357, Short.MAX_VALUE)))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSr)
                            .addComponent(cmbSr, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(281, 281, 281)
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDataAdmissao)
                                .addGap(14, 14, 14))
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataAdmissao))))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(177, 177, 177)
                                .addComponent(lblNumero)
                                .addGap(35, 35, 35)
                                .addComponent(lblBairro)
                                .addGap(191, 191, 191)
                                .addComponent(lblCidade))
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblCelUm)
                                .addGap(127, 127, 127)
                                .addComponent(lblCelDois)
                                .addGap(127, 127, 127)
                                .addComponent(lblCelTres)
                                .addGap(121, 121, 121)
                                .addComponent(lblEmail)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                    .addComponent(lblRG)
                                    .addGap(130, 130, 130)
                                    .addComponent(lblExpedicao)
                                    .addGap(56, 56, 56)
                                    .addComponent(lblNaturalidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosPessoaisLayout.createSequentialGroup()
                                    .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCPF))
                                    .addGap(6, 6, 6)
                                    .addComponent(txtExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCNH)
                                        .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(12, 12, 12)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloEleitor)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lblTituloEleitor)
                                .addContainerGap())
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstadoCivil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInstrucao)
                                    .addComponent(cmbInstrucao, 0, 1, Short.MAX_VALUE)))))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtCidade))))
        );
        pnDadosPessoaisLayout.setVerticalGroup(
            pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricula)
                            .addComponent(lblNome)
                            .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDataNascimento)
                                .addComponent(lblDataAdmissao))))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSr)))
                .addGap(1, 1, 1)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbSr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblReferencia)
                                .addComponent(lblCargoEmprego))
                            .addComponent(lblFuncaoGratificada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFuncaoGratificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblEmail1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbQuemAssinaPortaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRG)
                            .addComponent(lblExpedicao)
                            .addComponent(lblNaturalidade))
                        .addGap(6, 6, 6)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblCPF))
                            .addComponent(txtExpedicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblCNH))))
                    .addGroup(pnDadosPessoaisLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoCivil)
                            .addComponent(lblInstrucao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(lblTituloEleitor)))
                .addGap(6, 6, 6)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco)
                    .addComponent(lblNumero)
                    .addComponent(lblBairro)
                    .addComponent(lblCidade))
                .addGap(6, 6, 6)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelUm)
                    .addComponent(lblCelDois)
                    .addComponent(lblCelTres)
                    .addComponent(lblEmail))
                .addGap(6, 6, 6)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGravar)))
        );

        abaServidores.addTab("Dados Pessoais", pnDadosPessoais);

        lblNumeroPortariaNomeacao.setText("Nº da Portaria de Nomeação: ");

        lblNumeroDoConcurso.setText("Nº do Concurso:");

        lblLeiAtribuicaoCargoEmprego.setText("Lei com atribuição do cargo/emprego:");

        lblClassificacaoConcurso.setText("Classificação:");

        lblDataPortariaNomeacao.setText("Data Portaria de Nomeação:");

        lblReajusteCargoEmprego.setText("Lei com reajuste salarial do cargo/emprego:");

        lblRegimeJuridico.setText("Regime Jurídico:");

        cmbRegimeJuridico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLT", "ESTATUTÁRIO" }));

        chkCargoEmComissao.setText("Cargo em Comissão?");
        chkCargoEmComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCargoEmComissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCargoEmpregoLayout = new javax.swing.GroupLayout(pnCargoEmprego);
        pnCargoEmprego.setLayout(pnCargoEmpregoLayout);
        pnCargoEmpregoLayout.setHorizontalGroup(
            pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargoEmpregoLayout.createSequentialGroup()
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCargoEmpregoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addComponent(lblLeiAtribuicaoCargoEmprego)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addComponent(lblRegimeJuridico)
                                .addGap(24, 24, 24))))
                    .addGroup(pnCargoEmpregoLayout.createSequentialGroup()
                        .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCargoEmpregoLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(lblNumeroDoConcurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNumeroPortariaNomeacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRegimeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLeiAtribuicaoCargoEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPortariaNomeacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                        .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addComponent(lblReajusteCargoEmprego)
                                .addGap(18, 18, 18)
                                .addComponent(txtLeiReajusteCargoEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addComponent(lblDataPortariaNomeacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataPortariaNomeacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                                .addComponent(lblClassificacaoConcurso)
                                .addGap(18, 18, 18)
                                .addComponent(txtClassificacaoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCargoEmpregoLayout.createSequentialGroup()
                        .addComponent(chkCargoEmComissao)
                        .addContainerGap())))
        );
        pnCargoEmpregoLayout.setVerticalGroup(
            pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCargoEmpregoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegimeJuridico)
                    .addComponent(cmbRegimeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCargoEmComissao))
                .addGap(12, 12, 12)
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLeiAtribuicaoCargoEmprego)
                        .addComponent(txtLeiAtribuicaoCargoEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReajusteCargoEmprego)
                        .addComponent(txtLeiReajusteCargoEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroDoConcurso)
                        .addComponent(txtNumeroDoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtClassificacaoConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblClassificacaoConcurso)))
                .addGap(18, 18, 18)
                .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDataPortariaNomeacao)
                        .addComponent(txtDataPortariaNomeacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCargoEmpregoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroPortariaNomeacao)
                        .addComponent(txtNumeroPortariaNomeacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        abaServidores.addTab("Cargo/Emprego", pnCargoEmprego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaServidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaServidores)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        txtExpedicao.requestFocus();
    }//GEN-LAST:event_txtRGActionPerformed

    private void cmbSrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSrActionPerformed
        // TODO add your handling code here:
        if(cmbSr.getSelectedItem().equals("SR."))
        {
            String estadoCivil[] = {"SOLTEIRO", "CASADO", "SEPARADO", "DIVORCIADO", "VIÚVO"};
            final DefaultComboBoxModel model = new DefaultComboBoxModel(estadoCivil);
            
            cmbEstadoCivil.setModel(model);
        }
        else if(cmbSr.getSelectedItem().equals("SRA."))
        {
            String estadoCivil[] = {"SOLTEIRA", "CASADA", "SEPARADA", "DIVORCIADA", "VIÚVA"};
            final DefaultComboBoxModel model = new DefaultComboBoxModel(estadoCivil);
            
            cmbEstadoCivil.setModel(model);
        }      
        
        txtNome.requestFocus();
    }//GEN-LAST:event_cmbSrActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(!txtMatricula.getText().isEmpty() && !txtMatricula.isEnabled())
        {
            reiniciarCampos();
            destravarCampos();
        }
        else
        {
             botaoCadastrar();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void botaoCadastrar()
    {
        //CÓDIGO BOTÃO CADASTRAR
        //pegar item de combobox
        String cmbPronomeDeTratamentoConvertidoParaString = (String) this.cmbSr.getSelectedItem();
        String cmbInstrucao = (String) this.cmbInstrucao.getSelectedItem();
        String cmbEstadoCivil = (String) this.cmbEstadoCivil.getSelectedItem(); 
        String cmbQuemAssinaPortaria = (String) this.cmbQuemAssinaPortaria.getSelectedItem();
        String cmbRegimeJuridico = (String) this.cmbRegimeJuridico.getSelectedItem();
        

        //verificar se tem algum valor digitado no txtbox
        validarSeCamposEstaoComValores();
                
       if(!txtMatricula.getText().isEmpty() && !txtNome.getText().isEmpty() && !txtDataAdmissao.getText().equals("  /  /    ") && !txtDataNascimento.getText().equals("  /  /    ") && !txtCargo.getText().isEmpty() && !txtReferencia.getText().isEmpty() && !txtRG.getText().isEmpty() && !txtExpedicao.getText().isEmpty() && !txtNaturalidade.getText().isEmpty() && !cmbEstadoCivil.isEmpty() && !cmbInstrucao.isEmpty() && !txtCPF.getText().equals("   .   .   -  ") && !txtEndereco.getText().isEmpty() && !txtNumero.getText().isEmpty() && !txtBairro.getText().isEmpty() && !txtCidade.getText().isEmpty() && !txtCelUm.getText().equals("(  )       -    "))
       {
         //txtCelDois.getText().equals("(  )       -    ")) ? "" : txtCelDois.getText() operador ternario se txtcel dois tiver numero cadastrado pegue, senão deixe em branco
         ServidoresCadastrarFuncionarioControle controle = new ServidoresCadastrarFuncionarioControle(txtMatricula.getText(), cmbPronomeDeTratamentoConvertidoParaString, txtNome.getText(), txtDataAdmissao.getText(), txtDataNascimento.getText(), txtCargo.getText(), txtReferencia.getText(), txtFuncaoGratificada.getText(), cmbQuemAssinaPortaria, txtRG.getText(), txtExpedicao.getText(), txtNaturalidade.getText(), cmbEstadoCivil, cmbInstrucao, txtCPF.getText(), txtCNH.getText(), (txtTituloEleitor.getText().isEmpty()) ? "" : txtTituloEleitor.getText(), txtEndereco.getText(), txtNumero.getText(), txtBairro.getText(), txtCidade.getText(), txtCelUm.getText(), (txtCelDois.getText().equals("(  )       -    ")) ? "" : txtCelDois.getText(), (txtCelTres.getText().equals("(  )       -    ")) ? "" : txtCelTres.getText(), (txtEmail.getText().isEmpty()) ? "" : txtEmail.getText(), cmbRegimeJuridico, boolChkCargoEmComissao, txtLeiAtribuicaoCargoEmprego.getText(), txtLeiReajusteCargoEmprego.getText(), txtNumeroDoConcurso.getText(), txtClassificacaoConcurso.getText());  
         if(controle.getMensagem().equals("ok"))
         {
             JOptionPane.showMessageDialog(null, "CADASTRO REALIZADO COM SUCESSO!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
             reiniciarCampos(); 
         }
         else if(controle.getMensagem().equals("erro 1"))
         {
             JOptionPane.showMessageDialog(null, "FUNCIONÁRIO JÁ CADASTRADO NO BANCO DE DADOS.","ERRO",JOptionPane.ERROR_MESSAGE);
         }
       }
    }
    
    private void validarSeCamposEstaoComValores()
    {
       if(txtMatricula.getText().isEmpty())
       {
           lblMatricula.setForeground(Color.red);
       }
       else
       {
           lblMatricula.setForeground(Color.black);
       }

       if(txtNome.getText().isEmpty())
       {
           lblNome.setForeground(Color.red);
       }
       else
       {
           lblNome.setForeground(Color.black);
       }

       if(txtDataAdmissao.getText().equals("  /  /    "))
       {
           lblDataAdmissao.setForeground(Color.red);
       }
       else
       {
           lblDataAdmissao.setForeground(Color.black);
       }

       if(txtDataNascimento.getText().equals("  /  /    "))
       {
           lblDataNascimento.setForeground(Color.red);
       }
       else
       {
           lblDataNascimento.setForeground(Color.black);
       }

       if(txtCargo.getText().isEmpty())
       {
           lblCargoEmprego.setForeground(Color.red);
       }
       else
       {
           lblCargoEmprego.setForeground(Color.black);
       }

       if(txtReferencia.getText().isEmpty())
       {
           lblReferencia.setForeground(Color.red);
       }
       else
       {
           lblReferencia.setForeground(Color.black);
       }

       if(txtRG.getText().isEmpty())
       {
           lblRG.setForeground(Color.red);
       }
       else
       {
           lblRG.setForeground(Color.black);
       }

       if(txtExpedicao.getText().isEmpty())
       {
           lblExpedicao.setForeground(Color.red);
       }
       else
       {
           lblExpedicao.setForeground(Color.black);
       }

       if(txtNaturalidade.getText().isEmpty())
       {
           lblNaturalidade.setForeground(Color.red);
       }
       else
       {
           lblNaturalidade.setForeground(Color.black);
       }

       if(txtCPF.getText().equals("   .   .   -  "))
       {
           lblCPF.setForeground(Color.red);
       }
       else
       {
           lblCPF.setForeground(Color.black);
       }

       if(txtEndereco.getText().isEmpty())
       {
           lblEndereco.setForeground(Color.red);
       }
       else
       {
           lblEndereco.setForeground(Color.black);
       }

       if(txtNumero.getText().isEmpty())
       {
           lblNumero.setForeground(Color.red);
       }
       else
       {
           lblNumero.setForeground(Color.black);
       }

       if(txtBairro.getText().isEmpty())
       {
           lblBairro.setForeground(Color.red);
       }
       else
       {
           lblBairro.setForeground(Color.black);
       }

       if(txtCidade.getText().isEmpty())
       {
           lblCidade.setForeground(Color.red);
       }
       else
       {
           lblCidade.setForeground(Color.black);
       }

       if(txtCelUm.getText().equals("(  )       -    "))
       {
           lblCelUm.setForeground(Color.red);
       }
       else
       {
           lblCelUm.setForeground(Color.black);
       }
    }
    
    public void reiniciarCampos()
    {
        txtMatricula.setText("");
        cmbSr.setSelectedIndex(0);
        txtNome.setText("");
        txtDataAdmissao.setValue("");
        txtDataNascimento.setValue("");
        txtCargo.setText("");
        txtReferencia.setText("");
        txtFuncaoGratificada.setText("");
        txtRG.setText("");
        txtExpedicao.setText("");
        txtNaturalidade.setText("");
        cmbEstadoCivil.setSelectedIndex(0);
        cmbInstrucao.setSelectedIndex(5);
        txtCPF.setValue("");
        txtCNH.setText("");
        txtTituloEleitor.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtCelUm.setValue("");
        txtCelDois.setValue("");
        txtCelTres.setValue("");
        txtEmail.setText("");  
        cmbRegimeJuridico.setSelectedIndex(0);
        chkCargoEmComissao.setSelected(false);
        txtLeiAtribuicaoCargoEmprego.setText("");
        txtLeiReajusteCargoEmprego.setText("");
        txtNumeroDoConcurso.setText("");
        txtClassificacaoConcurso.setText("");
    }    
   
    public void travarCampos()
    {        
        txtMatricula.setEnabled(false);
        cmbSr.setEnabled(false);
        txtNome.setEnabled(false);
        txtDataAdmissao.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCargo.setEnabled(false);
        txtReferencia.setEnabled(false);
        txtFuncaoGratificada.setEnabled(false);
        txtRG.setEnabled(false);
        txtExpedicao.setEnabled(false);
        txtNaturalidade.setEnabled(false);
        cmbEstadoCivil.setEnabled(false);
        cmbInstrucao.setEnabled(false);
        txtCPF.setEnabled(false);
        txtCNH.setEnabled(false);
        txtTituloEleitor.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCelUm.setEnabled(false);
        txtCelDois.setEnabled(false);
        txtCelTres.setEnabled(false);
        txtEmail.setEnabled(false); 
        cmbRegimeJuridico.setEnabled(false);
        chkCargoEmComissao.setEnabled(false);
        txtLeiAtribuicaoCargoEmprego.setEnabled(false);
        txtLeiReajusteCargoEmprego.setEnabled(false);
        txtNumeroDoConcurso.setEnabled(false);
        txtClassificacaoConcurso.setEnabled(false);
    }
    
    public void destravarCampos()
    {
        txtMatricula.setEnabled(true);
        cmbSr.setEnabled(true);
        txtNome.setEnabled(true);
        txtDataAdmissao.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtCargo.setEnabled(true);
        txtReferencia.setEnabled(true);
        txtFuncaoGratificada.setEnabled(true);
        txtRG.setEnabled(true);
        txtExpedicao.setEnabled(true);
        txtNaturalidade.setEnabled(true);
        cmbEstadoCivil.setEnabled(true);
        cmbInstrucao.setEnabled(true);
        txtCPF.setEnabled(true);
        txtCNH.setEnabled(true);
        txtTituloEleitor.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtCelUm.setEnabled(true);
        txtCelDois.setEnabled(true);
        txtCelTres.setEnabled(true);
        txtEmail.setEnabled(true);     
        cmbRegimeJuridico.setEnabled(true);
        chkCargoEmComissao.setEnabled(true);
        txtLeiAtribuicaoCargoEmprego.setEnabled(true);
        txtLeiReajusteCargoEmprego.setEnabled(true);
        txtNumeroDoConcurso.setEnabled(true);
        txtClassificacaoConcurso.setEnabled(true);    
    }
    
    public void deixarLabelsComCorPreta()
    {
        lblMatricula.setForeground(Color.black);
        lblSr.setForeground(Color.black);
        lblNome.setForeground(Color.black);
        lblDataAdmissao.setForeground(Color.black);
        lblDataNascimento.setForeground(Color.black);
        lblCargoEmprego.setForeground(Color.black);
        lblReferencia.setForeground(Color.black);
        lblFuncaoGratificada.setForeground(Color.black);
        lblRG.setForeground(Color.black);
        lblExpedicao.setForeground(Color.black);
        lblNaturalidade.setForeground(Color.black);
        lblEstadoCivil.setForeground(Color.black);
        lblInstrucao.setForeground(Color.black);
        lblCPF.setForeground(Color.black);
        lblCNH.setForeground(Color.black);
        lblTituloEleitor.setForeground(Color.black);
        lblEndereco.setForeground(Color.black);
        lblNumero.setForeground(Color.black);
        lblBairro.setForeground(Color.black);
        lblCidade.setForeground(Color.black);
        lblCelUm.setForeground(Color.black);
        lblCelDois.setForeground(Color.black);
        lblCelTres.setForeground(Color.black);
        lblEmail.setForeground(Color.black);
        lblRegimeJuridico.setForeground(Color.black);
        lblLeiAtribuicaoCargoEmprego.setForeground(Color.black);
        lblReajusteCargoEmprego.setForeground(Color.black);
        lblNumeroDoConcurso.setForeground(Color.black);
        lblClassificacaoConcurso.setForeground(Color.black);
        
    }
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        frmPesquisarFuncionario frmPF = new frmPesquisarFuncionario(null, true);
        frmPF.setVisible(true);
        
        if(frmPF.getMensagem().equals("pode passar"))
        {        
            txtMatricula.setText(frmPF.getLista().get(frmPF.getIndex()).getMatricula());
            cmbSr.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getPronomeTratamento());
            txtNome.setText(frmPF.getLista().get(frmPF.getIndex()).getNome());
            txtDataAdmissao.setText(frmPF.getLista().get(frmPF.getIndex()).getDataAdmissao());
            txtDataNascimento.setText(frmPF.getLista().get(frmPF.getIndex()).getDataNascimento());
            txtCargo.setText(frmPF.getLista().get(frmPF.getIndex()).getCargo());
            txtReferencia.setText(frmPF.getLista().get(frmPF.getIndex()).getReferencia());
            txtRG.setText(frmPF.getLista().get(frmPF.getIndex()).getRg());
            txtNaturalidade.setText(frmPF.getLista().get(frmPF.getIndex()).getNaturalidade());
            cmbEstadoCivil.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getEstadoCivil());
            cmbInstrucao.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getInstrucao());
            txtCPF.setText(frmPF.getLista().get(frmPF.getIndex()).getCpf());
            txtCNH.setText(frmPF.getLista().get(frmPF.getIndex()).getCnh());
            txtTituloEleitor.setText(frmPF.getLista().get(frmPF.getIndex()).getTituloEleitor());
            txtEndereco.setText(frmPF.getLista().get(frmPF.getIndex()).getEndereco());
            txtNumero.setText(frmPF.getLista().get(frmPF.getIndex()).getNumero());
            txtBairro.setText(frmPF.getLista().get(frmPF.getIndex()).getBairro());
            txtCidade.setText(frmPF.getLista().get(frmPF.getIndex()).getCidade());
            txtCelUm.setText(frmPF.getLista().get(frmPF.getIndex()).getCelUm());
            txtCelDois.setText(frmPF.getLista().get(frmPF.getIndex()).getCelDois());
            txtCelTres.setText(frmPF.getLista().get(frmPF.getIndex()).getCelTres()); 
            txtEmail.setText(frmPF.getLista().get(frmPF.getIndex()).getEmail()); 
            cmbRegimeJuridico.setSelectedItem(frmPF.getLista().get(frmPF.getIndex()).getRegimeJuridico());
            chkCargoEmComissao.setSelected(frmPF.getLista().get(frmPF.getIndex()).isBoolChkCargoEmComissao());
            txtLeiAtribuicaoCargoEmprego.setText(frmPF.getLista().get(frmPF.getIndex()).getLeiAtribuicaoCargoEmprego());
            txtLeiReajusteCargoEmprego.setText(frmPF.getLista().get(frmPF.getIndex()).getLeiReajusteCargoEmprego());
            txtNumeroDoConcurso.setText(frmPF.getLista().get(frmPF.getIndex()).getNumeroConcurso());
            txtClassificacaoConcurso.setText(frmPF.getLista().get(frmPF.getIndex()).getClassificacaoConcurso());
        }
            travarCampos();
            deixarLabelsComCorPreta();
            btnCadastrar.setEnabled(true);
            btnAlterar.setEnabled(true);
            
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        destravarCampos();
        btnAlterar.setEnabled(false);
        btnCadastrar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnGravar.setEnabled(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
        txtNome.requestFocus();
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        txtDataNascimento.requestFocus();
        String mudarParaCaixaAlta = txtNome.getText().toUpperCase();
        txtNome.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        txtReferencia.requestFocus();
        String mudarParaCaixaAlta = txtCargo.getText().toUpperCase();
        txtCargo.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtFuncaoGratificadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncaoGratificadaActionPerformed
        cmbQuemAssinaPortaria.requestFocus();
        String mudarParaCaixaAlta = txtFuncaoGratificada.getText().toUpperCase();
        txtFuncaoGratificada.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtFuncaoGratificadaActionPerformed

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
        txtFuncaoGratificada.requestFocus();
        String mudarParaCaixaAlta = txtReferencia.getText().toUpperCase();
        txtReferencia.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void txtExpedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpedicaoActionPerformed
        txtNaturalidade.requestFocus();
        String mudarParaCaixaAlta = txtExpedicao.getText().toUpperCase();
        txtExpedicao.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtExpedicaoActionPerformed

    private void txtNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeActionPerformed
        cmbEstadoCivil.requestFocus();
        String mudarParaCaixaAlta = txtNaturalidade.getText().toUpperCase();
        txtNaturalidade.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNaturalidadeActionPerformed

    private void txtCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNHActionPerformed
        txtTituloEleitor.requestFocus();
        String mudarParaCaixaAlta = txtTituloEleitor.getText().toUpperCase();
        txtTituloEleitor.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCNHActionPerformed

    private void txtTituloEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloEleitorActionPerformed
        txtEndereco.requestFocus();
        String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
        txtEndereco.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtTituloEleitorActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        txtBairro.requestFocus();
        String mudarParaCaixaAlta = txtNumero.getText().toUpperCase();
        txtNumero.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        txtNumero.requestFocus();
        String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
        txtEndereco.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        txtCidade.requestFocus();
        String mudarParaCaixaAlta = txtBairro.getText().toUpperCase();
        txtBairro.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        txtCelUm.requestFocus();
        String mudarParaCaixaAlta = txtCidade.getText().toUpperCase();
        txtCidade.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        btnCadastrar.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
       if(txtNome.getText().isEmpty())
       {
           lblNome.setForeground(Color.red);           
       }
       else
       {
           lblNome.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNome.getText().toUpperCase();
           txtNome.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusLost
     if(txtCargo.getText().isEmpty())
       {
           lblCargoEmprego.setForeground(Color.red);
       }
       else
       {
           lblCargoEmprego.setForeground(Color.black);
           String mudarParaCaixaAlta = txtCargo.getText().toUpperCase();
           txtCargo.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtCargoFocusLost

    private void txtReferenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReferenciaFocusLost
       if(txtReferencia.getText().isEmpty())
       {
           lblReferencia.setForeground(Color.red);
       }
       else
       {
           lblReferencia.setForeground(Color.black);
           String mudarParaCaixaAlta = txtReferencia.getText().toUpperCase();
           txtReferencia.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtReferenciaFocusLost

    private void txtFuncaoGratificadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFuncaoGratificadaFocusLost
           lblFuncaoGratificada.setForeground(Color.black);
           String mudarParaCaixaAlta = txtFuncaoGratificada.getText().toUpperCase();
           txtFuncaoGratificada.setText(mudarParaCaixaAlta);
    }//GEN-LAST:event_txtFuncaoGratificadaFocusLost

    private void txtRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusLost
         if(txtRG.getText().isEmpty())
       {
           lblRG.setForeground(Color.red);
       }
       else
       {
           lblRG.setForeground(Color.black);
           String mudarParaCaixaAlta = txtRG.getText().toUpperCase();
           txtRG.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtRGFocusLost

    private void txtExpedicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpedicaoFocusLost
       if(txtExpedicao.getText().isEmpty())
       {
           lblExpedicao.setForeground(Color.red);
       }
       else
       {
           lblExpedicao.setForeground(Color.black);
           String mudarParaCaixaAlta = txtExpedicao.getText().toUpperCase();
           txtExpedicao.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtExpedicaoFocusLost

    private void txtNaturalidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNaturalidadeFocusLost
        if(txtNaturalidade.getText().isEmpty())
       {
           lblNaturalidade.setForeground(Color.red);
       }
       else
       {
           lblNaturalidade.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNaturalidade.getText().toUpperCase();
           txtNaturalidade.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNaturalidadeFocusLost

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        if(txtEndereco.getText().isEmpty())
       {
           lblEndereco.setForeground(Color.red);
       }
       else
       {
           lblEndereco.setForeground(Color.black);
           String mudarParaCaixaAlta = txtEndereco.getText().toUpperCase();
           txtEndereco.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
      if(txtNumero.getText().isEmpty())
       {
           lblNumero.setForeground(Color.red);
       }
       else
       {
           lblNumero.setForeground(Color.black);
           String mudarParaCaixaAlta = txtNumero.getText().toUpperCase();
           txtNumero.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusLost
        if(txtBairro.getText().isEmpty())
       {
           lblBairro.setForeground(Color.red);
       }
       else
       {
           lblBairro.setForeground(Color.black);
           String mudarParaCaixaAlta = txtBairro.getText().toUpperCase();
           txtBairro.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtBairroFocusLost

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        if(txtCidade.getText().isEmpty())
       {
           lblCidade.setForeground(Color.red);
       }
       else
       {
           lblCidade.setForeground(Color.black);
           String mudarParaCaixaAlta = txtCidade.getText().toUpperCase();
           txtCidade.setText(mudarParaCaixaAlta);
       }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
           botaoCadastrar();
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    private void txtDataAdmissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataAdmissaoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCargo.requestFocus();
    }   
    }//GEN-LAST:event_txtDataAdmissaoKeyPressed

    private void txtDataAdmissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataAdmissaoFocusLost
    if(txtDataAdmissao.getText().equals("  /  /    "))
    {
        lblDataAdmissao.setForeground(Color.red);
        txtDataAdmissao.setValue("");
    }
    else
    {
        lblDataAdmissao.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtDataAdmissaoFocusLost

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
    if(txtCPF.getText().equals("   .   .   -  "))
    {
        lblCPF.setForeground(Color.red);
        txtCPF.setValue("");
    }  
    else
    {
        lblCPF.setForeground(Color.black);
    }
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
       txtCNH.requestFocus();
    }
    }//GEN-LAST:event_txtCPFKeyPressed

    private void txtDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoFocusLost
    if(txtDataNascimento.getText().equals("  /  /    "))
    {
       lblDataNascimento.setForeground(Color.red);
       txtDataNascimento.setValue("");
    }
    else
    {
        lblDataNascimento.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtDataNascimentoFocusLost

    private void txtDataNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataNascimentoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtDataAdmissao.requestFocus();
    }
    }//GEN-LAST:event_txtDataNascimentoKeyPressed

    private void txtCelUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelUmActionPerformed
        txtCelDois.requestFocus();
    }//GEN-LAST:event_txtCelUmActionPerformed

    private void txtCelUmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelUmFocusLost
    if(txtCelUm.getText().equals("(  )       -    "))
    {
        lblCelUm.setForeground(Color.red);
        txtCelUm.setValue("");
    }
    else
    {
        lblCelUm.setForeground(Color.black);
    } 
    }//GEN-LAST:event_txtCelUmFocusLost

    private void txtCelUmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelUmKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCelDois.requestFocus();
    }
    }//GEN-LAST:event_txtCelUmKeyPressed

    private void txtCelDoisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelDoisKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtCelTres.requestFocus();
    }
    }//GEN-LAST:event_txtCelDoisKeyPressed

    private void txtCelTresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelTresKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        txtEmail.requestFocus();
    }        
    }//GEN-LAST:event_txtCelTresKeyPressed

    private void cmbInstrucaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbInstrucaoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {        
        txtCPF.requestFocus();
    }
    }//GEN-LAST:event_cmbInstrucaoKeyPressed

    private void cmbEstadoCivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbEstadoCivilKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        cmbInstrucao.requestFocus();
    }
    }//GEN-LAST:event_cmbEstadoCivilKeyPressed

    private void txtCelTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelTresActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtCelTresActionPerformed

    private void txtCelDoisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelDoisFocusLost
    if(txtCelDois.getText().equals("(  )       -    "))
    {
        txtCelDois.setValue("");
    }
    }//GEN-LAST:event_txtCelDoisFocusLost

    private void txtCelTresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelTresFocusLost
    if(txtCelTres.getText().equals("(  )       -    "))
    {
        txtCelTres.setValue("");
    }
    }//GEN-LAST:event_txtCelTresFocusLost

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        travarCampos();
        btnGravar.setEnabled(false);
        btnCadastrar.setEnabled(true);
        btnPesquisar.setEnabled(true);
    }//GEN-LAST:event_btnGravarActionPerformed

    private void cmbQuemAssinaPortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuemAssinaPortariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQuemAssinaPortariaActionPerformed

    private void cmbQuemAssinaPortariaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbQuemAssinaPortariaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQuemAssinaPortariaFocusLost

    private void cmbQuemAssinaPortariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbQuemAssinaPortariaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtRG.requestFocus();
        }
    }//GEN-LAST:event_cmbQuemAssinaPortariaKeyPressed

    private void chkCargoEmComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCargoEmComissaoActionPerformed
        // TODO add your handling code here:
        if(chkCargoEmComissao.isSelected())
        {
            this.boolChkCargoEmComissao = true;
        }
        else
        {
            this.boolChkCargoEmComissao = false;
        }
        
        System.out.println(boolChkCargoEmComissao);
    }//GEN-LAST:event_chkCargoEmComissaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmServidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmServidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmServidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmServidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmServidores dialog = new frmServidores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaServidores;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JCheckBox chkCargoEmComissao;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbInstrucao;
    private javax.swing.JComboBox<String> cmbQuemAssinaPortaria;
    private javax.swing.JComboBox<String> cmbRegimeJuridico;
    private javax.swing.JComboBox<String> cmbSr;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCNH;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCargoEmprego;
    private javax.swing.JLabel lblCelDois;
    private javax.swing.JLabel lblCelTres;
    private javax.swing.JLabel lblCelUm;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblClassificacaoConcurso;
    private javax.swing.JLabel lblDataAdmissao;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblDataPortariaNomeacao;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblExpedicao;
    private javax.swing.JLabel lblFuncaoGratificada;
    private javax.swing.JLabel lblInstrucao;
    private javax.swing.JLabel lblLeiAtribuicaoCargoEmprego;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroDoConcurso;
    private javax.swing.JLabel lblNumeroPortariaNomeacao;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblReajusteCargoEmprego;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblRegimeJuridico;
    private javax.swing.JLabel lblSr;
    private javax.swing.JLabel lblTituloEleitor;
    private javax.swing.JPanel pnCargoEmprego;
    private javax.swing.JPanel pnDadosPessoais;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNH;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtCelDois;
    private javax.swing.JFormattedTextField txtCelTres;
    private javax.swing.JFormattedTextField txtCelUm;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtClassificacaoConcurso;
    private javax.swing.JFormattedTextField txtDataAdmissao;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtDataPortariaNomeacao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtExpedicao;
    private javax.swing.JTextField txtFuncaoGratificada;
    private javax.swing.JTextField txtLeiAtribuicaoCargoEmprego;
    private javax.swing.JTextField txtLeiReajusteCargoEmprego;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroDoConcurso;
    private javax.swing.JTextField txtNumeroPortariaNomeacao;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTituloEleitor;
    // End of variables declaration//GEN-END:variables
 
}
